// Generated by gencpp from file delphi_mrr_msgs/LrosSignalsActualValues.msg
// DO NOT EDIT!


#ifndef DELPHI_MRR_MSGS_MESSAGE_LROSSIGNALSACTUALVALUES_H
#define DELPHI_MRR_MSGS_MESSAGE_LROSSIGNALSACTUALVALUES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace delphi_mrr_msgs
{
template <class ContainerAllocator>
struct LrosSignalsActualValues_
{
  typedef LrosSignalsActualValues_<ContainerAllocator> Type;

  LrosSignalsActualValues_()
    : header()
    , can_power_supp_ford(0)
    , can_power_motive_ford(0)
    , can_cruise_status_ford(0.0)
    , can_veh_batt_volt(0)
    , can_gear_position(0)
    , can_ambient_temp(0.0)
    , can_ign_status(0)  {
    }
  LrosSignalsActualValues_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , can_power_supp_ford(0)
    , can_power_motive_ford(0)
    , can_cruise_status_ford(0.0)
    , can_veh_batt_volt(0)
    , can_gear_position(0)
    , can_ambient_temp(0.0)
    , can_ign_status(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _can_power_supp_ford_type;
  _can_power_supp_ford_type can_power_supp_ford;

   typedef uint8_t _can_power_motive_ford_type;
  _can_power_motive_ford_type can_power_motive_ford;

   typedef float _can_cruise_status_ford_type;
  _can_cruise_status_ford_type can_cruise_status_ford;

   typedef uint8_t _can_veh_batt_volt_type;
  _can_veh_batt_volt_type can_veh_batt_volt;

   typedef uint16_t _can_gear_position_type;
  _can_gear_position_type can_gear_position;

   typedef float _can_ambient_temp_type;
  _can_ambient_temp_type can_ambient_temp;

   typedef uint8_t _can_ign_status_type;
  _can_ign_status_type can_ign_status;





  typedef boost::shared_ptr< ::delphi_mrr_msgs::LrosSignalsActualValues_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::delphi_mrr_msgs::LrosSignalsActualValues_<ContainerAllocator> const> ConstPtr;

}; // struct LrosSignalsActualValues_

typedef ::delphi_mrr_msgs::LrosSignalsActualValues_<std::allocator<void> > LrosSignalsActualValues;

typedef boost::shared_ptr< ::delphi_mrr_msgs::LrosSignalsActualValues > LrosSignalsActualValuesPtr;
typedef boost::shared_ptr< ::delphi_mrr_msgs::LrosSignalsActualValues const> LrosSignalsActualValuesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::delphi_mrr_msgs::LrosSignalsActualValues_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::delphi_mrr_msgs::LrosSignalsActualValues_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace delphi_mrr_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'delphi_mrr_msgs': ['/metamoto/catkin_ws/src/astuff_sensor_msgs/delphi_mrr_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::delphi_mrr_msgs::LrosSignalsActualValues_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delphi_mrr_msgs::LrosSignalsActualValues_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delphi_mrr_msgs::LrosSignalsActualValues_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delphi_mrr_msgs::LrosSignalsActualValues_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delphi_mrr_msgs::LrosSignalsActualValues_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delphi_mrr_msgs::LrosSignalsActualValues_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::delphi_mrr_msgs::LrosSignalsActualValues_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0716096f6271f8e0b8822fbc1fb61142";
  }

  static const char* value(const ::delphi_mrr_msgs::LrosSignalsActualValues_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0716096f6271f8e0ULL;
  static const uint64_t static_value2 = 0xb8822fbc1fb61142ULL;
};

template<class ContainerAllocator>
struct DataType< ::delphi_mrr_msgs::LrosSignalsActualValues_<ContainerAllocator> >
{
  static const char* value()
  {
    return "delphi_mrr_msgs/LrosSignalsActualValues";
  }

  static const char* value(const ::delphi_mrr_msgs::LrosSignalsActualValues_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::delphi_mrr_msgs::LrosSignalsActualValues_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
\n\
uint8 	  can_power_supp_ford\n\
uint8 	  can_power_motive_ford\n\
float32   can_cruise_status_ford\n\
uint8 	  can_veh_batt_volt\n\
uint16 	  can_gear_position\n\
float32   can_ambient_temp\n\
uint8 	  can_ign_status\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::delphi_mrr_msgs::LrosSignalsActualValues_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::delphi_mrr_msgs::LrosSignalsActualValues_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.can_power_supp_ford);
      stream.next(m.can_power_motive_ford);
      stream.next(m.can_cruise_status_ford);
      stream.next(m.can_veh_batt_volt);
      stream.next(m.can_gear_position);
      stream.next(m.can_ambient_temp);
      stream.next(m.can_ign_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LrosSignalsActualValues_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::delphi_mrr_msgs::LrosSignalsActualValues_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::delphi_mrr_msgs::LrosSignalsActualValues_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "can_power_supp_ford: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.can_power_supp_ford);
    s << indent << "can_power_motive_ford: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.can_power_motive_ford);
    s << indent << "can_cruise_status_ford: ";
    Printer<float>::stream(s, indent + "  ", v.can_cruise_status_ford);
    s << indent << "can_veh_batt_volt: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.can_veh_batt_volt);
    s << indent << "can_gear_position: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.can_gear_position);
    s << indent << "can_ambient_temp: ";
    Printer<float>::stream(s, indent + "  ", v.can_ambient_temp);
    s << indent << "can_ign_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.can_ign_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DELPHI_MRR_MSGS_MESSAGE_LROSSIGNALSACTUALVALUES_H
