# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metamoto/services/map.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from metamoto.types import roads_pb2 as metamoto_dot_types_dot_roads__pb2
from metamoto.types import vector3_pb2 as metamoto_dot_types_dot_vector3__pb2
from metamoto.types import waypoint_pb2 as metamoto_dot_types_dot_waypoint__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='metamoto/services/map.proto',
  package='metamoto.services',
  syntax='proto3',
  serialized_options=_b('\n\025com.metamoto.servicesP\001'),
  serialized_pb=_b('\n\x1bmetamoto/services/map.proto\x12\x11metamoto.services\x1a\x1ametamoto/types/roads.proto\x1a\x1cmetamoto/types/vector3.proto\x1a\x1dmetamoto/types/waypoint.proto\"\x1a\n\x18MapGetRoadNetworkRequest\"K\n\x16MapGetRoadNetworkReply\x12\x31\n\x0croad_network\x18\x01 \x01(\x0b\x32\x1b.metamoto.types.RoadNetwork\"a\n\x15MapToRoadPointRequest\x12,\n\x0bworld_point\x18\x01 \x01(\x0b\x32\x17.metamoto.types.Vector3\x12\x1a\n\x12vertical_tolerance\x18\x02 \x01(\x02\"E\n\x13MapToRoadPointReply\x12.\n\x0broad_points\x18\x01 \x03(\x0b\x32\x19.metamoto.types.RoadPoint\"G\n\x16MapToWorldPointRequest\x12-\n\nroad_point\x18\x01 \x01(\x0b\x32\x19.metamoto.types.RoadPoint\"D\n\x14MapToWorldPointReply\x12,\n\x0bworld_point\x18\x01 \x01(\x0b\x32\x17.metamoto.types.Vector3\"E\n\x14MapGetHeadingRequest\x12-\n\nroad_point\x18\x01 \x01(\x0b\x32\x19.metamoto.types.RoadPoint\">\n\x12MapGetHeadingReply\x12(\n\x07heading\x18\x01 \x01(\x0b\x32\x17.metamoto.types.Vector3\"m\n\x11MapGetPathRequest\x12,\n\nfrom_point\x18\x01 \x01(\x0b\x32\x18.metamoto.types.Waypoint\x12*\n\x08to_point\x18\x02 \x01(\x0b\x32\x18.metamoto.types.Waypoint\"9\n\x0fMapGetPathReply\x12&\n\x04path\x18\x01 \x03(\x0b\x32\x18.metamoto.types.Waypoint2\xf1\x03\n\x03Map\x12j\n\x0eGetRoadNetwork\x12+.metamoto.services.MapGetRoadNetworkRequest\x1a).metamoto.services.MapGetRoadNetworkReply\"\x00\x12\x61\n\x0bToRoadPoint\x12(.metamoto.services.MapToRoadPointRequest\x1a&.metamoto.services.MapToRoadPointReply\"\x00\x12\x64\n\x0cToWorldPoint\x12).metamoto.services.MapToWorldPointRequest\x1a\'.metamoto.services.MapToWorldPointReply\"\x00\x12^\n\nGetHeading\x12\'.metamoto.services.MapGetHeadingRequest\x1a%.metamoto.services.MapGetHeadingReply\"\x00\x12U\n\x07GetPath\x12$.metamoto.services.MapGetPathRequest\x1a\".metamoto.services.MapGetPathReply\"\x00\x42\x19\n\x15\x63om.metamoto.servicesP\x01\x62\x06proto3')
  ,
  dependencies=[metamoto_dot_types_dot_roads__pb2.DESCRIPTOR,metamoto_dot_types_dot_vector3__pb2.DESCRIPTOR,metamoto_dot_types_dot_waypoint__pb2.DESCRIPTOR,])




_MAPGETROADNETWORKREQUEST = _descriptor.Descriptor(
  name='MapGetRoadNetworkRequest',
  full_name='metamoto.services.MapGetRoadNetworkRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=165,
)


_MAPGETROADNETWORKREPLY = _descriptor.Descriptor(
  name='MapGetRoadNetworkReply',
  full_name='metamoto.services.MapGetRoadNetworkReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='road_network', full_name='metamoto.services.MapGetRoadNetworkReply.road_network', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=242,
)


_MAPTOROADPOINTREQUEST = _descriptor.Descriptor(
  name='MapToRoadPointRequest',
  full_name='metamoto.services.MapToRoadPointRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='world_point', full_name='metamoto.services.MapToRoadPointRequest.world_point', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vertical_tolerance', full_name='metamoto.services.MapToRoadPointRequest.vertical_tolerance', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=244,
  serialized_end=341,
)


_MAPTOROADPOINTREPLY = _descriptor.Descriptor(
  name='MapToRoadPointReply',
  full_name='metamoto.services.MapToRoadPointReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='road_points', full_name='metamoto.services.MapToRoadPointReply.road_points', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=343,
  serialized_end=412,
)


_MAPTOWORLDPOINTREQUEST = _descriptor.Descriptor(
  name='MapToWorldPointRequest',
  full_name='metamoto.services.MapToWorldPointRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='road_point', full_name='metamoto.services.MapToWorldPointRequest.road_point', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=414,
  serialized_end=485,
)


_MAPTOWORLDPOINTREPLY = _descriptor.Descriptor(
  name='MapToWorldPointReply',
  full_name='metamoto.services.MapToWorldPointReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='world_point', full_name='metamoto.services.MapToWorldPointReply.world_point', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=487,
  serialized_end=555,
)


_MAPGETHEADINGREQUEST = _descriptor.Descriptor(
  name='MapGetHeadingRequest',
  full_name='metamoto.services.MapGetHeadingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='road_point', full_name='metamoto.services.MapGetHeadingRequest.road_point', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=557,
  serialized_end=626,
)


_MAPGETHEADINGREPLY = _descriptor.Descriptor(
  name='MapGetHeadingReply',
  full_name='metamoto.services.MapGetHeadingReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='heading', full_name='metamoto.services.MapGetHeadingReply.heading', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=628,
  serialized_end=690,
)


_MAPGETPATHREQUEST = _descriptor.Descriptor(
  name='MapGetPathRequest',
  full_name='metamoto.services.MapGetPathRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='from_point', full_name='metamoto.services.MapGetPathRequest.from_point', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to_point', full_name='metamoto.services.MapGetPathRequest.to_point', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=692,
  serialized_end=801,
)


_MAPGETPATHREPLY = _descriptor.Descriptor(
  name='MapGetPathReply',
  full_name='metamoto.services.MapGetPathReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='metamoto.services.MapGetPathReply.path', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=803,
  serialized_end=860,
)

_MAPGETROADNETWORKREPLY.fields_by_name['road_network'].message_type = metamoto_dot_types_dot_roads__pb2._ROADNETWORK
_MAPTOROADPOINTREQUEST.fields_by_name['world_point'].message_type = metamoto_dot_types_dot_vector3__pb2._VECTOR3
_MAPTOROADPOINTREPLY.fields_by_name['road_points'].message_type = metamoto_dot_types_dot_roads__pb2._ROADPOINT
_MAPTOWORLDPOINTREQUEST.fields_by_name['road_point'].message_type = metamoto_dot_types_dot_roads__pb2._ROADPOINT
_MAPTOWORLDPOINTREPLY.fields_by_name['world_point'].message_type = metamoto_dot_types_dot_vector3__pb2._VECTOR3
_MAPGETHEADINGREQUEST.fields_by_name['road_point'].message_type = metamoto_dot_types_dot_roads__pb2._ROADPOINT
_MAPGETHEADINGREPLY.fields_by_name['heading'].message_type = metamoto_dot_types_dot_vector3__pb2._VECTOR3
_MAPGETPATHREQUEST.fields_by_name['from_point'].message_type = metamoto_dot_types_dot_waypoint__pb2._WAYPOINT
_MAPGETPATHREQUEST.fields_by_name['to_point'].message_type = metamoto_dot_types_dot_waypoint__pb2._WAYPOINT
_MAPGETPATHREPLY.fields_by_name['path'].message_type = metamoto_dot_types_dot_waypoint__pb2._WAYPOINT
DESCRIPTOR.message_types_by_name['MapGetRoadNetworkRequest'] = _MAPGETROADNETWORKREQUEST
DESCRIPTOR.message_types_by_name['MapGetRoadNetworkReply'] = _MAPGETROADNETWORKREPLY
DESCRIPTOR.message_types_by_name['MapToRoadPointRequest'] = _MAPTOROADPOINTREQUEST
DESCRIPTOR.message_types_by_name['MapToRoadPointReply'] = _MAPTOROADPOINTREPLY
DESCRIPTOR.message_types_by_name['MapToWorldPointRequest'] = _MAPTOWORLDPOINTREQUEST
DESCRIPTOR.message_types_by_name['MapToWorldPointReply'] = _MAPTOWORLDPOINTREPLY
DESCRIPTOR.message_types_by_name['MapGetHeadingRequest'] = _MAPGETHEADINGREQUEST
DESCRIPTOR.message_types_by_name['MapGetHeadingReply'] = _MAPGETHEADINGREPLY
DESCRIPTOR.message_types_by_name['MapGetPathRequest'] = _MAPGETPATHREQUEST
DESCRIPTOR.message_types_by_name['MapGetPathReply'] = _MAPGETPATHREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MapGetRoadNetworkRequest = _reflection.GeneratedProtocolMessageType('MapGetRoadNetworkRequest', (_message.Message,), dict(
  DESCRIPTOR = _MAPGETROADNETWORKREQUEST,
  __module__ = 'metamoto.services.map_pb2'
  # @@protoc_insertion_point(class_scope:metamoto.services.MapGetRoadNetworkRequest)
  ))
_sym_db.RegisterMessage(MapGetRoadNetworkRequest)

MapGetRoadNetworkReply = _reflection.GeneratedProtocolMessageType('MapGetRoadNetworkReply', (_message.Message,), dict(
  DESCRIPTOR = _MAPGETROADNETWORKREPLY,
  __module__ = 'metamoto.services.map_pb2'
  # @@protoc_insertion_point(class_scope:metamoto.services.MapGetRoadNetworkReply)
  ))
_sym_db.RegisterMessage(MapGetRoadNetworkReply)

MapToRoadPointRequest = _reflection.GeneratedProtocolMessageType('MapToRoadPointRequest', (_message.Message,), dict(
  DESCRIPTOR = _MAPTOROADPOINTREQUEST,
  __module__ = 'metamoto.services.map_pb2'
  # @@protoc_insertion_point(class_scope:metamoto.services.MapToRoadPointRequest)
  ))
_sym_db.RegisterMessage(MapToRoadPointRequest)

MapToRoadPointReply = _reflection.GeneratedProtocolMessageType('MapToRoadPointReply', (_message.Message,), dict(
  DESCRIPTOR = _MAPTOROADPOINTREPLY,
  __module__ = 'metamoto.services.map_pb2'
  # @@protoc_insertion_point(class_scope:metamoto.services.MapToRoadPointReply)
  ))
_sym_db.RegisterMessage(MapToRoadPointReply)

MapToWorldPointRequest = _reflection.GeneratedProtocolMessageType('MapToWorldPointRequest', (_message.Message,), dict(
  DESCRIPTOR = _MAPTOWORLDPOINTREQUEST,
  __module__ = 'metamoto.services.map_pb2'
  # @@protoc_insertion_point(class_scope:metamoto.services.MapToWorldPointRequest)
  ))
_sym_db.RegisterMessage(MapToWorldPointRequest)

MapToWorldPointReply = _reflection.GeneratedProtocolMessageType('MapToWorldPointReply', (_message.Message,), dict(
  DESCRIPTOR = _MAPTOWORLDPOINTREPLY,
  __module__ = 'metamoto.services.map_pb2'
  # @@protoc_insertion_point(class_scope:metamoto.services.MapToWorldPointReply)
  ))
_sym_db.RegisterMessage(MapToWorldPointReply)

MapGetHeadingRequest = _reflection.GeneratedProtocolMessageType('MapGetHeadingRequest', (_message.Message,), dict(
  DESCRIPTOR = _MAPGETHEADINGREQUEST,
  __module__ = 'metamoto.services.map_pb2'
  # @@protoc_insertion_point(class_scope:metamoto.services.MapGetHeadingRequest)
  ))
_sym_db.RegisterMessage(MapGetHeadingRequest)

MapGetHeadingReply = _reflection.GeneratedProtocolMessageType('MapGetHeadingReply', (_message.Message,), dict(
  DESCRIPTOR = _MAPGETHEADINGREPLY,
  __module__ = 'metamoto.services.map_pb2'
  # @@protoc_insertion_point(class_scope:metamoto.services.MapGetHeadingReply)
  ))
_sym_db.RegisterMessage(MapGetHeadingReply)

MapGetPathRequest = _reflection.GeneratedProtocolMessageType('MapGetPathRequest', (_message.Message,), dict(
  DESCRIPTOR = _MAPGETPATHREQUEST,
  __module__ = 'metamoto.services.map_pb2'
  # @@protoc_insertion_point(class_scope:metamoto.services.MapGetPathRequest)
  ))
_sym_db.RegisterMessage(MapGetPathRequest)

MapGetPathReply = _reflection.GeneratedProtocolMessageType('MapGetPathReply', (_message.Message,), dict(
  DESCRIPTOR = _MAPGETPATHREPLY,
  __module__ = 'metamoto.services.map_pb2'
  # @@protoc_insertion_point(class_scope:metamoto.services.MapGetPathReply)
  ))
_sym_db.RegisterMessage(MapGetPathReply)


DESCRIPTOR._options = None

_MAP = _descriptor.ServiceDescriptor(
  name='Map',
  full_name='metamoto.services.Map',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=863,
  serialized_end=1360,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetRoadNetwork',
    full_name='metamoto.services.Map.GetRoadNetwork',
    index=0,
    containing_service=None,
    input_type=_MAPGETROADNETWORKREQUEST,
    output_type=_MAPGETROADNETWORKREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ToRoadPoint',
    full_name='metamoto.services.Map.ToRoadPoint',
    index=1,
    containing_service=None,
    input_type=_MAPTOROADPOINTREQUEST,
    output_type=_MAPTOROADPOINTREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ToWorldPoint',
    full_name='metamoto.services.Map.ToWorldPoint',
    index=2,
    containing_service=None,
    input_type=_MAPTOWORLDPOINTREQUEST,
    output_type=_MAPTOWORLDPOINTREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetHeading',
    full_name='metamoto.services.Map.GetHeading',
    index=3,
    containing_service=None,
    input_type=_MAPGETHEADINGREQUEST,
    output_type=_MAPGETHEADINGREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetPath',
    full_name='metamoto.services.Map.GetPath',
    index=4,
    containing_service=None,
    input_type=_MAPGETPATHREQUEST,
    output_type=_MAPGETPATHREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MAP)

DESCRIPTOR.services_by_name['Map'] = _MAP

# @@protoc_insertion_point(module_scope)
