(cl:in-package delphi_mrr_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          CAN_VEHICLE_STAT-VAL
          CAN_VEHICLE_STAT
          CAN_DAY_NIGHT_STATUS-VAL
          CAN_DAY_NIGHT_STATUS
          CAN_WIPER_STATUS-VAL
          CAN_WIPER_STATUS
          CAN_YAW_RATE_VALIDITY-VAL
          CAN_YAW_RATE_VALIDITY
          CAN_YAW_RATE-VAL
          CAN_YAW_RATE
          CAN_VEHICLE_SPEED_VALIDITY-VAL
          CAN_VEHICLE_SPEED_VALIDITY
          CAN_VEHICLE_SPEED_DIRECTION-VAL
          CAN_VEHICLE_SPEED_DIRECTION
          CAN_VEHICLE_SPEED-VAL
          CAN_VEHICLE_SPEED
))