(cl:in-package delphi_mrr_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          CAN_MRR_UPSIDE_DOWN-VAL
          CAN_MRR_UPSIDE_DOWN
          CAN_BLOCKAGE_FILTER_OUTPUT-VAL
          CAN_BLOCKAGE_FILTER_OUTPUT
          CAN_ANGLE_MISALIGNMENT_HDR-VAL
          CAN_ANGLE_MISALIGNMENT_HDR
          CAN_USE_ANGLE_MISALIGNMENT-VAL
          CAN_USE_ANGLE_MISALIGNMENT
          CAN_BLOCKAGE_DISABLE-VAL
          CAN_BLOCKAGE_DISABLE
          CAN_SCAN_INDEX_ACK-VAL
          CAN_SCAN_INDEX_ACK
))