# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metamoto/messages/data_bus_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from metamoto.messages import vehicle_state_pb2 as metamoto_dot_messages_dot_vehicle__state__pb2
from metamoto.messages import vehicle_controls_pb2 as metamoto_dot_messages_dot_vehicle__controls__pb2
from metamoto.messages import camera_pb2 as metamoto_dot_messages_dot_camera__pb2
from metamoto.messages import lidar_pb2 as metamoto_dot_messages_dot_lidar__pb2
from metamoto.messages import radar_pb2 as metamoto_dot_messages_dot_radar__pb2
from metamoto.messages import gps_pb2 as metamoto_dot_messages_dot_gps__pb2
from metamoto.messages import imu_pb2 as metamoto_dot_messages_dot_imu__pb2
from metamoto.messages import ground_truth_pb2 as metamoto_dot_messages_dot_ground__truth__pb2
from metamoto.messages import localizer_pb2 as metamoto_dot_messages_dot_localizer__pb2
from metamoto.messages import v2x_pb2 as metamoto_dot_messages_dot_v2x__pb2
from metamoto.messages import perception_pb2 as metamoto_dot_messages_dot_perception__pb2
from metamoto.messages import event_pb2 as metamoto_dot_messages_dot_event__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='metamoto/messages/data_bus_message.proto',
  package='metamoto.messages',
  syntax='proto3',
  serialized_options=_b('\252\002\021Metamoto.Messages'),
  serialized_pb=_b('\n(metamoto/messages/data_bus_message.proto\x12\x11metamoto.messages\x1a\x19google/protobuf/any.proto\x1a%metamoto/messages/vehicle_state.proto\x1a(metamoto/messages/vehicle_controls.proto\x1a\x1emetamoto/messages/camera.proto\x1a\x1dmetamoto/messages/lidar.proto\x1a\x1dmetamoto/messages/radar.proto\x1a\x1bmetamoto/messages/gps.proto\x1a\x1bmetamoto/messages/imu.proto\x1a$metamoto/messages/ground_truth.proto\x1a!metamoto/messages/localizer.proto\x1a\x1bmetamoto/messages/v2x.proto\x1a\"metamoto/messages/perception.proto\x1a\x1dmetamoto/messages/event.proto\"\x16\n\x06Header\x12\x0c\n\x04time\x18\x01 \x01(\x01\"\xad\x05\n\x0e\x44\x61taBusMessage\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.metamoto.messages.Header\x12\x38\n\rvehicle_state\x18\x02 \x01(\x0b\x32\x1f.metamoto.messages.VehicleStateH\x00\x12>\n\x10vehicle_controls\x18\x03 \x01(\x0b\x32\".metamoto.messages.VehicleControlsH\x00\x12+\n\x06\x63\x61mera\x18\x04 \x01(\x0b\x32\x19.metamoto.messages.CameraH\x00\x12)\n\x05lidar\x18\x05 \x01(\x0b\x32\x18.metamoto.messages.LidarH\x00\x12)\n\x05radar\x18\x06 \x01(\x0b\x32\x18.metamoto.messages.RadarH\x00\x12%\n\x03gps\x18\x07 \x01(\x0b\x32\x16.metamoto.messages.GPSH\x00\x12%\n\x03imu\x18\x08 \x01(\x0b\x32\x16.metamoto.messages.IMUH\x00\x12\x31\n\tlocalizer\x18\t \x01(\x0b\x32\x1c.metamoto.messages.LocalizerH\x00\x12%\n\x03v2x\x18\n \x01(\x0b\x32\x16.metamoto.messages.V2XH\x00\x12)\n\x05\x65vent\x18\x0b \x01(\x0b\x32\x18.metamoto.messages.EventH\x00\x12\x33\n\nperception\x18\x0c \x01(\x0b\x32\x1d.metamoto.messages.PerceptionH\x00\x12\x36\n\x0cground_truth\x18\x1e \x01(\x0b\x32\x1e.metamoto.messages.GroundTruthH\x00\x12%\n\x05other\x18\x64 \x01(\x0b\x32\x14.google.protobuf.AnyH\x00\x42\x0c\n\ndata_oneofB\x14\xaa\x02\x11Metamoto.Messagesb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,metamoto_dot_messages_dot_vehicle__state__pb2.DESCRIPTOR,metamoto_dot_messages_dot_vehicle__controls__pb2.DESCRIPTOR,metamoto_dot_messages_dot_camera__pb2.DESCRIPTOR,metamoto_dot_messages_dot_lidar__pb2.DESCRIPTOR,metamoto_dot_messages_dot_radar__pb2.DESCRIPTOR,metamoto_dot_messages_dot_gps__pb2.DESCRIPTOR,metamoto_dot_messages_dot_imu__pb2.DESCRIPTOR,metamoto_dot_messages_dot_ground__truth__pb2.DESCRIPTOR,metamoto_dot_messages_dot_localizer__pb2.DESCRIPTOR,metamoto_dot_messages_dot_v2x__pb2.DESCRIPTOR,metamoto_dot_messages_dot_perception__pb2.DESCRIPTOR,metamoto_dot_messages_dot_event__pb2.DESCRIPTOR,])




_HEADER = _descriptor.Descriptor(
  name='Header',
  full_name='metamoto.messages.Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='metamoto.messages.Header.time', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=492,
  serialized_end=514,
)


_DATABUSMESSAGE = _descriptor.Descriptor(
  name='DataBusMessage',
  full_name='metamoto.messages.DataBusMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='metamoto.messages.DataBusMessage.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vehicle_state', full_name='metamoto.messages.DataBusMessage.vehicle_state', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vehicle_controls', full_name='metamoto.messages.DataBusMessage.vehicle_controls', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='camera', full_name='metamoto.messages.DataBusMessage.camera', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lidar', full_name='metamoto.messages.DataBusMessage.lidar', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='radar', full_name='metamoto.messages.DataBusMessage.radar', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gps', full_name='metamoto.messages.DataBusMessage.gps', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imu', full_name='metamoto.messages.DataBusMessage.imu', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='localizer', full_name='metamoto.messages.DataBusMessage.localizer', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v2x', full_name='metamoto.messages.DataBusMessage.v2x', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event', full_name='metamoto.messages.DataBusMessage.event', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='perception', full_name='metamoto.messages.DataBusMessage.perception', index=11,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ground_truth', full_name='metamoto.messages.DataBusMessage.ground_truth', index=12,
      number=30, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='other', full_name='metamoto.messages.DataBusMessage.other', index=13,
      number=100, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data_oneof', full_name='metamoto.messages.DataBusMessage.data_oneof',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=517,
  serialized_end=1202,
)

_DATABUSMESSAGE.fields_by_name['header'].message_type = _HEADER
_DATABUSMESSAGE.fields_by_name['vehicle_state'].message_type = metamoto_dot_messages_dot_vehicle__state__pb2._VEHICLESTATE
_DATABUSMESSAGE.fields_by_name['vehicle_controls'].message_type = metamoto_dot_messages_dot_vehicle__controls__pb2._VEHICLECONTROLS
_DATABUSMESSAGE.fields_by_name['camera'].message_type = metamoto_dot_messages_dot_camera__pb2._CAMERA
_DATABUSMESSAGE.fields_by_name['lidar'].message_type = metamoto_dot_messages_dot_lidar__pb2._LIDAR
_DATABUSMESSAGE.fields_by_name['radar'].message_type = metamoto_dot_messages_dot_radar__pb2._RADAR
_DATABUSMESSAGE.fields_by_name['gps'].message_type = metamoto_dot_messages_dot_gps__pb2._GPS
_DATABUSMESSAGE.fields_by_name['imu'].message_type = metamoto_dot_messages_dot_imu__pb2._IMU
_DATABUSMESSAGE.fields_by_name['localizer'].message_type = metamoto_dot_messages_dot_localizer__pb2._LOCALIZER
_DATABUSMESSAGE.fields_by_name['v2x'].message_type = metamoto_dot_messages_dot_v2x__pb2._V2X
_DATABUSMESSAGE.fields_by_name['event'].message_type = metamoto_dot_messages_dot_event__pb2._EVENT
_DATABUSMESSAGE.fields_by_name['perception'].message_type = metamoto_dot_messages_dot_perception__pb2._PERCEPTION
_DATABUSMESSAGE.fields_by_name['ground_truth'].message_type = metamoto_dot_messages_dot_ground__truth__pb2._GROUNDTRUTH
_DATABUSMESSAGE.fields_by_name['other'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_DATABUSMESSAGE.oneofs_by_name['data_oneof'].fields.append(
  _DATABUSMESSAGE.fields_by_name['vehicle_state'])
_DATABUSMESSAGE.fields_by_name['vehicle_state'].containing_oneof = _DATABUSMESSAGE.oneofs_by_name['data_oneof']
_DATABUSMESSAGE.oneofs_by_name['data_oneof'].fields.append(
  _DATABUSMESSAGE.fields_by_name['vehicle_controls'])
_DATABUSMESSAGE.fields_by_name['vehicle_controls'].containing_oneof = _DATABUSMESSAGE.oneofs_by_name['data_oneof']
_DATABUSMESSAGE.oneofs_by_name['data_oneof'].fields.append(
  _DATABUSMESSAGE.fields_by_name['camera'])
_DATABUSMESSAGE.fields_by_name['camera'].containing_oneof = _DATABUSMESSAGE.oneofs_by_name['data_oneof']
_DATABUSMESSAGE.oneofs_by_name['data_oneof'].fields.append(
  _DATABUSMESSAGE.fields_by_name['lidar'])
_DATABUSMESSAGE.fields_by_name['lidar'].containing_oneof = _DATABUSMESSAGE.oneofs_by_name['data_oneof']
_DATABUSMESSAGE.oneofs_by_name['data_oneof'].fields.append(
  _DATABUSMESSAGE.fields_by_name['radar'])
_DATABUSMESSAGE.fields_by_name['radar'].containing_oneof = _DATABUSMESSAGE.oneofs_by_name['data_oneof']
_DATABUSMESSAGE.oneofs_by_name['data_oneof'].fields.append(
  _DATABUSMESSAGE.fields_by_name['gps'])
_DATABUSMESSAGE.fields_by_name['gps'].containing_oneof = _DATABUSMESSAGE.oneofs_by_name['data_oneof']
_DATABUSMESSAGE.oneofs_by_name['data_oneof'].fields.append(
  _DATABUSMESSAGE.fields_by_name['imu'])
_DATABUSMESSAGE.fields_by_name['imu'].containing_oneof = _DATABUSMESSAGE.oneofs_by_name['data_oneof']
_DATABUSMESSAGE.oneofs_by_name['data_oneof'].fields.append(
  _DATABUSMESSAGE.fields_by_name['localizer'])
_DATABUSMESSAGE.fields_by_name['localizer'].containing_oneof = _DATABUSMESSAGE.oneofs_by_name['data_oneof']
_DATABUSMESSAGE.oneofs_by_name['data_oneof'].fields.append(
  _DATABUSMESSAGE.fields_by_name['v2x'])
_DATABUSMESSAGE.fields_by_name['v2x'].containing_oneof = _DATABUSMESSAGE.oneofs_by_name['data_oneof']
_DATABUSMESSAGE.oneofs_by_name['data_oneof'].fields.append(
  _DATABUSMESSAGE.fields_by_name['event'])
_DATABUSMESSAGE.fields_by_name['event'].containing_oneof = _DATABUSMESSAGE.oneofs_by_name['data_oneof']
_DATABUSMESSAGE.oneofs_by_name['data_oneof'].fields.append(
  _DATABUSMESSAGE.fields_by_name['perception'])
_DATABUSMESSAGE.fields_by_name['perception'].containing_oneof = _DATABUSMESSAGE.oneofs_by_name['data_oneof']
_DATABUSMESSAGE.oneofs_by_name['data_oneof'].fields.append(
  _DATABUSMESSAGE.fields_by_name['ground_truth'])
_DATABUSMESSAGE.fields_by_name['ground_truth'].containing_oneof = _DATABUSMESSAGE.oneofs_by_name['data_oneof']
_DATABUSMESSAGE.oneofs_by_name['data_oneof'].fields.append(
  _DATABUSMESSAGE.fields_by_name['other'])
_DATABUSMESSAGE.fields_by_name['other'].containing_oneof = _DATABUSMESSAGE.oneofs_by_name['data_oneof']
DESCRIPTOR.message_types_by_name['Header'] = _HEADER
DESCRIPTOR.message_types_by_name['DataBusMessage'] = _DATABUSMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Header = _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), dict(
  DESCRIPTOR = _HEADER,
  __module__ = 'metamoto.messages.data_bus_message_pb2'
  # @@protoc_insertion_point(class_scope:metamoto.messages.Header)
  ))
_sym_db.RegisterMessage(Header)

DataBusMessage = _reflection.GeneratedProtocolMessageType('DataBusMessage', (_message.Message,), dict(
  DESCRIPTOR = _DATABUSMESSAGE,
  __module__ = 'metamoto.messages.data_bus_message_pb2'
  # @@protoc_insertion_point(class_scope:metamoto.messages.DataBusMessage)
  ))
_sym_db.RegisterMessage(DataBusMessage)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
