# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metamoto/messages/perception.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from metamoto.types import perception_object_pb2 as metamoto_dot_types_dot_perception__object__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='metamoto/messages/perception.proto',
  package='metamoto.messages',
  syntax='proto3',
  serialized_options=_b('\252\002\021Metamoto.Messages'),
  serialized_pb=_b('\n\"metamoto/messages/perception.proto\x12\x11metamoto.messages\x1a&metamoto/types/perception_object.proto\"?\n\nPerception\x12\x31\n\x07objects\x18\x01 \x03(\x0b\x32 .metamoto.types.PerceptionObjectB\x14\xaa\x02\x11Metamoto.Messagesb\x06proto3')
  ,
  dependencies=[metamoto_dot_types_dot_perception__object__pb2.DESCRIPTOR,])




_PERCEPTION = _descriptor.Descriptor(
  name='Perception',
  full_name='metamoto.messages.Perception',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='objects', full_name='metamoto.messages.Perception.objects', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=160,
)

_PERCEPTION.fields_by_name['objects'].message_type = metamoto_dot_types_dot_perception__object__pb2._PERCEPTIONOBJECT
DESCRIPTOR.message_types_by_name['Perception'] = _PERCEPTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Perception = _reflection.GeneratedProtocolMessageType('Perception', (_message.Message,), dict(
  DESCRIPTOR = _PERCEPTION,
  __module__ = 'metamoto.messages.perception_pb2'
  # @@protoc_insertion_point(class_scope:metamoto.messages.Perception)
  ))
_sym_db.RegisterMessage(Perception)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
