# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metamoto/messages/vehicle_state.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from metamoto.types import pose_pb2 as metamoto_dot_types_dot_pose__pb2
from metamoto.types import roads_pb2 as metamoto_dot_types_dot_roads__pb2
from metamoto.types import vehicle_pb2 as metamoto_dot_types_dot_vehicle__pb2
from metamoto.types import velocity_pb2 as metamoto_dot_types_dot_velocity__pb2
from metamoto.types import acceleration_pb2 as metamoto_dot_types_dot_acceleration__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='metamoto/messages/vehicle_state.proto',
  package='metamoto.messages',
  syntax='proto3',
  serialized_options=_b('\252\002\021Metamoto.Messages'),
  serialized_pb=_b('\n%metamoto/messages/vehicle_state.proto\x12\x11metamoto.messages\x1a\x19metamoto/types/pose.proto\x1a\x1ametamoto/types/roads.proto\x1a\x1cmetamoto/types/vehicle.proto\x1a\x1dmetamoto/types/velocity.proto\x1a!metamoto/types/acceleration.proto\"\xe4\x04\n\x0cVehicleState\x12\"\n\x04pose\x18\x01 \x01(\x0b\x32\x14.metamoto.types.Pose\x12*\n\x08velocity\x18\x02 \x01(\x0b\x32\x18.metamoto.types.Velocity\x12\x32\n\x0c\x61\x63\x63\x65leration\x18\x03 \x01(\x0b\x32\x1c.metamoto.types.Acceleration\x12-\n\nroad_point\x18\x04 \x03(\x0b\x32\x19.metamoto.types.RoadPoint\x12\x13\n\x0bsteer_angle\x18\x05 \x01(\x02\x12\x10\n\x08throttle\x18\x06 \x01(\x02\x12\r\n\x05\x62rake\x18\x07 \x01(\x02\x12\r\n\x05speed\x18\x08 \x01(\x02\x12;\n\rgear_selector\x18\t \x01(\x0e\x32$.metamoto.types.Vehicle.GearSelector\x12\x0c\n\x04gear\x18\n \x01(\x05\x12\x0b\n\x03rpm\x18\x0b \x01(\x02\x12=\n\x0bturn_signal\x18\x0c \x01(\x0e\x32(.metamoto.types.Vehicle.SignalLightState\x12\x37\n\x0bhead_lights\x18\r \x01(\x0e\x32\".metamoto.types.Vehicle.LightState\x12:\n\x06wheels\x18\x0f \x03(\x0b\x32*.metamoto.messages.VehicleState.WheelState\x12\x13\n\x0bother_state\x18\x10 \x03(\x02\x1a;\n\nWheelState\x12\x18\n\x10\x61ngular_velocity\x18\x01 \x01(\x02\x12\x13\n\x0bsteer_angle\x18\x02 \x01(\x02\x42\x14\xaa\x02\x11Metamoto.Messagesb\x06proto3')
  ,
  dependencies=[metamoto_dot_types_dot_pose__pb2.DESCRIPTOR,metamoto_dot_types_dot_roads__pb2.DESCRIPTOR,metamoto_dot_types_dot_vehicle__pb2.DESCRIPTOR,metamoto_dot_types_dot_velocity__pb2.DESCRIPTOR,metamoto_dot_types_dot_acceleration__pb2.DESCRIPTOR,])




_VEHICLESTATE_WHEELSTATE = _descriptor.Descriptor(
  name='WheelState',
  full_name='metamoto.messages.VehicleState.WheelState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='angular_velocity', full_name='metamoto.messages.VehicleState.WheelState.angular_velocity', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='steer_angle', full_name='metamoto.messages.VehicleState.WheelState.steer_angle', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=765,
  serialized_end=824,
)

_VEHICLESTATE = _descriptor.Descriptor(
  name='VehicleState',
  full_name='metamoto.messages.VehicleState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pose', full_name='metamoto.messages.VehicleState.pose', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='velocity', full_name='metamoto.messages.VehicleState.velocity', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acceleration', full_name='metamoto.messages.VehicleState.acceleration', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='road_point', full_name='metamoto.messages.VehicleState.road_point', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='steer_angle', full_name='metamoto.messages.VehicleState.steer_angle', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='throttle', full_name='metamoto.messages.VehicleState.throttle', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='brake', full_name='metamoto.messages.VehicleState.brake', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speed', full_name='metamoto.messages.VehicleState.speed', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gear_selector', full_name='metamoto.messages.VehicleState.gear_selector', index=8,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gear', full_name='metamoto.messages.VehicleState.gear', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rpm', full_name='metamoto.messages.VehicleState.rpm', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='turn_signal', full_name='metamoto.messages.VehicleState.turn_signal', index=11,
      number=12, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='head_lights', full_name='metamoto.messages.VehicleState.head_lights', index=12,
      number=13, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wheels', full_name='metamoto.messages.VehicleState.wheels', index=13,
      number=15, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='other_state', full_name='metamoto.messages.VehicleState.other_state', index=14,
      number=16, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_VEHICLESTATE_WHEELSTATE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=212,
  serialized_end=824,
)

_VEHICLESTATE_WHEELSTATE.containing_type = _VEHICLESTATE
_VEHICLESTATE.fields_by_name['pose'].message_type = metamoto_dot_types_dot_pose__pb2._POSE
_VEHICLESTATE.fields_by_name['velocity'].message_type = metamoto_dot_types_dot_velocity__pb2._VELOCITY
_VEHICLESTATE.fields_by_name['acceleration'].message_type = metamoto_dot_types_dot_acceleration__pb2._ACCELERATION
_VEHICLESTATE.fields_by_name['road_point'].message_type = metamoto_dot_types_dot_roads__pb2._ROADPOINT
_VEHICLESTATE.fields_by_name['gear_selector'].enum_type = metamoto_dot_types_dot_vehicle__pb2._VEHICLE_GEARSELECTOR
_VEHICLESTATE.fields_by_name['turn_signal'].enum_type = metamoto_dot_types_dot_vehicle__pb2._VEHICLE_SIGNALLIGHTSTATE
_VEHICLESTATE.fields_by_name['head_lights'].enum_type = metamoto_dot_types_dot_vehicle__pb2._VEHICLE_LIGHTSTATE
_VEHICLESTATE.fields_by_name['wheels'].message_type = _VEHICLESTATE_WHEELSTATE
DESCRIPTOR.message_types_by_name['VehicleState'] = _VEHICLESTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VehicleState = _reflection.GeneratedProtocolMessageType('VehicleState', (_message.Message,), dict(

  WheelState = _reflection.GeneratedProtocolMessageType('WheelState', (_message.Message,), dict(
    DESCRIPTOR = _VEHICLESTATE_WHEELSTATE,
    __module__ = 'metamoto.messages.vehicle_state_pb2'
    # @@protoc_insertion_point(class_scope:metamoto.messages.VehicleState.WheelState)
    ))
  ,
  DESCRIPTOR = _VEHICLESTATE,
  __module__ = 'metamoto.messages.vehicle_state_pb2'
  # @@protoc_insertion_point(class_scope:metamoto.messages.VehicleState)
  ))
_sym_db.RegisterMessage(VehicleState)
_sym_db.RegisterMessage(VehicleState.WheelState)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
