# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metamoto/types/normal_distribution.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='metamoto/types/normal_distribution.proto',
  package='metamoto.types',
  syntax='proto3',
  serialized_options=_b('\252\002\016Metamoto.Types'),
  serialized_pb=_b('\n(metamoto/types/normal_distribution.proto\x12\x0emetamoto.types\"3\n\x12NormalDistribution\x12\x0c\n\x04mean\x18\x01 \x01(\x01\x12\x0f\n\x07std_dev\x18\x02 \x01(\x01\x42\x11\xaa\x02\x0eMetamoto.Typesb\x06proto3')
)




_NORMALDISTRIBUTION = _descriptor.Descriptor(
  name='NormalDistribution',
  full_name='metamoto.types.NormalDistribution',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mean', full_name='metamoto.types.NormalDistribution.mean', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='std_dev', full_name='metamoto.types.NormalDistribution.std_dev', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=111,
)

DESCRIPTOR.message_types_by_name['NormalDistribution'] = _NORMALDISTRIBUTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NormalDistribution = _reflection.GeneratedProtocolMessageType('NormalDistribution', (_message.Message,), dict(
  DESCRIPTOR = _NORMALDISTRIBUTION,
  __module__ = 'metamoto.types.normal_distribution_pb2'
  # @@protoc_insertion_point(class_scope:metamoto.types.NormalDistribution)
  ))
_sym_db.RegisterMessage(NormalDistribution)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
