# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metamoto/types/pedestrian.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from metamoto.types import acceleration_pb2 as metamoto_dot_types_dot_acceleration__pb2
from metamoto.types import pose_pb2 as metamoto_dot_types_dot_pose__pb2
from metamoto.types import shape_pb2 as metamoto_dot_types_dot_shape__pb2
from metamoto.types import velocity_pb2 as metamoto_dot_types_dot_velocity__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='metamoto/types/pedestrian.proto',
  package='metamoto.types',
  syntax='proto3',
  serialized_options=_b('\252\002\016Metamoto.Types'),
  serialized_pb=_b('\n\x1fmetamoto/types/pedestrian.proto\x12\x0emetamoto.types\x1a!metamoto/types/acceleration.proto\x1a\x19metamoto/types/pose.proto\x1a\x1ametamoto/types/shape.proto\x1a\x1dmetamoto/types/velocity.proto\"\xbf\x02\n\nPedestrian\x12\n\n\x02id\x18\x01 \x01(\t\x12\"\n\x04pose\x18\x02 \x01(\x0b\x32\x14.metamoto.types.Pose\x12*\n\x08velocity\x18\x03 \x01(\x0b\x32\x18.metamoto.types.Velocity\x12\x32\n\x0c\x61\x63\x63\x65leration\x18\x04 \x01(\x0b\x32\x1c.metamoto.types.Acceleration\x12$\n\x05shape\x18\x05 \x01(\x0b\x32\x15.metamoto.types.Shape\x12-\n\x04type\x18\x06 \x01(\x0e\x32\x1f.metamoto.types.Pedestrian.Type\"L\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05OTHER\x10\x01\x12\t\n\x05\x41\x44ULT\x10\x02\x12\t\n\x05\x43HILD\x10\x03\x12\n\n\x06\x41NIMAL\x10\x04\x12\n\n\x06RUNNER\x10\x05\x42\x11\xaa\x02\x0eMetamoto.Typesb\x06proto3')
  ,
  dependencies=[metamoto_dot_types_dot_acceleration__pb2.DESCRIPTOR,metamoto_dot_types_dot_pose__pb2.DESCRIPTOR,metamoto_dot_types_dot_shape__pb2.DESCRIPTOR,metamoto_dot_types_dot_velocity__pb2.DESCRIPTOR,])



_PEDESTRIAN_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='metamoto.types.Pedestrian.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OTHER', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADULT', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHILD', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ANIMAL', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUNNER', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=416,
  serialized_end=492,
)
_sym_db.RegisterEnumDescriptor(_PEDESTRIAN_TYPE)


_PEDESTRIAN = _descriptor.Descriptor(
  name='Pedestrian',
  full_name='metamoto.types.Pedestrian',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='metamoto.types.Pedestrian.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pose', full_name='metamoto.types.Pedestrian.pose', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='velocity', full_name='metamoto.types.Pedestrian.velocity', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acceleration', full_name='metamoto.types.Pedestrian.acceleration', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shape', full_name='metamoto.types.Pedestrian.shape', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='metamoto.types.Pedestrian.type', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PEDESTRIAN_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=492,
)

_PEDESTRIAN.fields_by_name['pose'].message_type = metamoto_dot_types_dot_pose__pb2._POSE
_PEDESTRIAN.fields_by_name['velocity'].message_type = metamoto_dot_types_dot_velocity__pb2._VELOCITY
_PEDESTRIAN.fields_by_name['acceleration'].message_type = metamoto_dot_types_dot_acceleration__pb2._ACCELERATION
_PEDESTRIAN.fields_by_name['shape'].message_type = metamoto_dot_types_dot_shape__pb2._SHAPE
_PEDESTRIAN.fields_by_name['type'].enum_type = _PEDESTRIAN_TYPE
_PEDESTRIAN_TYPE.containing_type = _PEDESTRIAN
DESCRIPTOR.message_types_by_name['Pedestrian'] = _PEDESTRIAN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Pedestrian = _reflection.GeneratedProtocolMessageType('Pedestrian', (_message.Message,), dict(
  DESCRIPTOR = _PEDESTRIAN,
  __module__ = 'metamoto.types.pedestrian_pb2'
  # @@protoc_insertion_point(class_scope:metamoto.types.Pedestrian)
  ))
_sym_db.RegisterMessage(Pedestrian)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
