# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metamoto/types/pose.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from metamoto.types import quaternion_pb2 as metamoto_dot_types_dot_quaternion__pb2
from metamoto.types import vector3_pb2 as metamoto_dot_types_dot_vector3__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='metamoto/types/pose.proto',
  package='metamoto.types',
  syntax='proto3',
  serialized_options=_b('\252\002\016Metamoto.Types'),
  serialized_pb=_b('\n\x19metamoto/types/pose.proto\x12\x0emetamoto.types\x1a\x1fmetamoto/types/quaternion.proto\x1a\x1cmetamoto/types/vector3.proto\"b\n\x04Pose\x12)\n\x08position\x18\x01 \x01(\x0b\x32\x17.metamoto.types.Vector3\x12/\n\x0borientation\x18\x02 \x01(\x0b\x32\x1a.metamoto.types.QuaternionB\x11\xaa\x02\x0eMetamoto.Typesb\x06proto3')
  ,
  dependencies=[metamoto_dot_types_dot_quaternion__pb2.DESCRIPTOR,metamoto_dot_types_dot_vector3__pb2.DESCRIPTOR,])




_POSE = _descriptor.Descriptor(
  name='Pose',
  full_name='metamoto.types.Pose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='metamoto.types.Pose.position', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='metamoto.types.Pose.orientation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=206,
)

_POSE.fields_by_name['position'].message_type = metamoto_dot_types_dot_vector3__pb2._VECTOR3
_POSE.fields_by_name['orientation'].message_type = metamoto_dot_types_dot_quaternion__pb2._QUATERNION
DESCRIPTOR.message_types_by_name['Pose'] = _POSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Pose = _reflection.GeneratedProtocolMessageType('Pose', (_message.Message,), dict(
  DESCRIPTOR = _POSE,
  __module__ = 'metamoto.types.pose_pb2'
  # @@protoc_insertion_point(class_scope:metamoto.types.Pose)
  ))
_sym_db.RegisterMessage(Pose)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
