# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metamoto/types/rigid_body.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from metamoto.types import pose_pb2 as metamoto_dot_types_dot_pose__pb2
from metamoto.types import velocity_pb2 as metamoto_dot_types_dot_velocity__pb2
from metamoto.types import vector3_pb2 as metamoto_dot_types_dot_vector3__pb2
from metamoto.types import enumerations_pb2 as metamoto_dot_types_dot_enumerations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='metamoto/types/rigid_body.proto',
  package='metamoto.types',
  syntax='proto3',
  serialized_options=_b('\252\002\016Metamoto.Types'),
  serialized_pb=_b('\n\x1fmetamoto/types/rigid_body.proto\x12\x0emetamoto.types\x1a\x19metamoto/types/pose.proto\x1a\x1dmetamoto/types/velocity.proto\x1a\x1cmetamoto/types/vector3.proto\x1a!metamoto/types/enumerations.proto\"\xb0\x01\n\x0bTireContact\x12\'\n\x06\x63\x65nter\x18\x01 \x01(\x0b\x32\x17.metamoto.types.Vector3\x12\'\n\x06normal\x18\x02 \x01(\x0b\x32\x17.metamoto.types.Vector3\x12.\n\x08material\x18\x03 \x01(\x0e\x32\x1c.metamoto.types.MaterialType\x12\x0f\n\x07wetness\x18\x04 \x01(\x02\x12\x0e\n\x06puddle\x18\x05 \x01(\x02\"\x86\x01\n\tRigidBody\x12\"\n\x04pose\x18\x01 \x01(\x0b\x32\x14.metamoto.types.Pose\x12)\n\x0bwheels_pose\x18\x02 \x03(\x0b\x32\x14.metamoto.types.Pose\x12*\n\x08velocity\x18\x03 \x01(\x0b\x32\x18.metamoto.types.VelocityB\x11\xaa\x02\x0eMetamoto.Typesb\x06proto3')
  ,
  dependencies=[metamoto_dot_types_dot_pose__pb2.DESCRIPTOR,metamoto_dot_types_dot_velocity__pb2.DESCRIPTOR,metamoto_dot_types_dot_vector3__pb2.DESCRIPTOR,metamoto_dot_types_dot_enumerations__pb2.DESCRIPTOR,])




_TIRECONTACT = _descriptor.Descriptor(
  name='TireContact',
  full_name='metamoto.types.TireContact',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='center', full_name='metamoto.types.TireContact.center', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='normal', full_name='metamoto.types.TireContact.normal', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='material', full_name='metamoto.types.TireContact.material', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wetness', full_name='metamoto.types.TireContact.wetness', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='puddle', full_name='metamoto.types.TireContact.puddle', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=351,
)


_RIGIDBODY = _descriptor.Descriptor(
  name='RigidBody',
  full_name='metamoto.types.RigidBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pose', full_name='metamoto.types.RigidBody.pose', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wheels_pose', full_name='metamoto.types.RigidBody.wheels_pose', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='velocity', full_name='metamoto.types.RigidBody.velocity', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=354,
  serialized_end=488,
)

_TIRECONTACT.fields_by_name['center'].message_type = metamoto_dot_types_dot_vector3__pb2._VECTOR3
_TIRECONTACT.fields_by_name['normal'].message_type = metamoto_dot_types_dot_vector3__pb2._VECTOR3
_TIRECONTACT.fields_by_name['material'].enum_type = metamoto_dot_types_dot_enumerations__pb2._MATERIALTYPE
_RIGIDBODY.fields_by_name['pose'].message_type = metamoto_dot_types_dot_pose__pb2._POSE
_RIGIDBODY.fields_by_name['wheels_pose'].message_type = metamoto_dot_types_dot_pose__pb2._POSE
_RIGIDBODY.fields_by_name['velocity'].message_type = metamoto_dot_types_dot_velocity__pb2._VELOCITY
DESCRIPTOR.message_types_by_name['TireContact'] = _TIRECONTACT
DESCRIPTOR.message_types_by_name['RigidBody'] = _RIGIDBODY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TireContact = _reflection.GeneratedProtocolMessageType('TireContact', (_message.Message,), dict(
  DESCRIPTOR = _TIRECONTACT,
  __module__ = 'metamoto.types.rigid_body_pb2'
  # @@protoc_insertion_point(class_scope:metamoto.types.TireContact)
  ))
_sym_db.RegisterMessage(TireContact)

RigidBody = _reflection.GeneratedProtocolMessageType('RigidBody', (_message.Message,), dict(
  DESCRIPTOR = _RIGIDBODY,
  __module__ = 'metamoto.types.rigid_body_pb2'
  # @@protoc_insertion_point(class_scope:metamoto.types.RigidBody)
  ))
_sym_db.RegisterMessage(RigidBody)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
