# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metamoto/types/terrain.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from metamoto.types import vector3_pb2 as metamoto_dot_types_dot_vector3__pb2
from metamoto.types import enumerations_pb2 as metamoto_dot_types_dot_enumerations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='metamoto/types/terrain.proto',
  package='metamoto.types',
  syntax='proto3',
  serialized_options=_b('\252\002\016Metamoto.Types'),
  serialized_pb=_b('\n\x1cmetamoto/types/terrain.proto\x12\x0emetamoto.types\x1a\x1cmetamoto/types/vector3.proto\x1a!metamoto/types/enumerations.proto\"\xd4\x01\n\x07Terrain\x12\x0c\n\x04name\x18\x01 \x01(\t\x12)\n\x08vertices\x18\x02 \x03(\x0b\x32\x17.metamoto.types.Vector3\x12(\n\x07normals\x18\x03 \x03(\x0b\x32\x17.metamoto.types.Vector3\x12\x11\n\twetnesses\x18\x04 \x03(\x02\x12\x0f\n\x07puddles\x18\x05 \x03(\x02\x12\x11\n\ttriangles\x18\x06 \x03(\x05\x12/\n\tmaterials\x18\x07 \x03(\x0e\x32\x1c.metamoto.types.MaterialTypeB\x11\xaa\x02\x0eMetamoto.Typesb\x06proto3')
  ,
  dependencies=[metamoto_dot_types_dot_vector3__pb2.DESCRIPTOR,metamoto_dot_types_dot_enumerations__pb2.DESCRIPTOR,])




_TERRAIN = _descriptor.Descriptor(
  name='Terrain',
  full_name='metamoto.types.Terrain',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='metamoto.types.Terrain.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vertices', full_name='metamoto.types.Terrain.vertices', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='normals', full_name='metamoto.types.Terrain.normals', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wetnesses', full_name='metamoto.types.Terrain.wetnesses', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='puddles', full_name='metamoto.types.Terrain.puddles', index=4,
      number=5, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='triangles', full_name='metamoto.types.Terrain.triangles', index=5,
      number=6, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='materials', full_name='metamoto.types.Terrain.materials', index=6,
      number=7, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=326,
)

_TERRAIN.fields_by_name['vertices'].message_type = metamoto_dot_types_dot_vector3__pb2._VECTOR3
_TERRAIN.fields_by_name['normals'].message_type = metamoto_dot_types_dot_vector3__pb2._VECTOR3
_TERRAIN.fields_by_name['materials'].enum_type = metamoto_dot_types_dot_enumerations__pb2._MATERIALTYPE
DESCRIPTOR.message_types_by_name['Terrain'] = _TERRAIN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Terrain = _reflection.GeneratedProtocolMessageType('Terrain', (_message.Message,), dict(
  DESCRIPTOR = _TERRAIN,
  __module__ = 'metamoto.types.terrain_pb2'
  # @@protoc_insertion_point(class_scope:metamoto.types.Terrain)
  ))
_sym_db.RegisterMessage(Terrain)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
