# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metamoto/types/traffic_light.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from metamoto.types import pose_pb2 as metamoto_dot_types_dot_pose__pb2
from metamoto.types import shape_pb2 as metamoto_dot_types_dot_shape__pb2
from metamoto.types import signal_configuration_pb2 as metamoto_dot_types_dot_signal__configuration__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='metamoto/types/traffic_light.proto',
  package='metamoto.types',
  syntax='proto3',
  serialized_options=_b('\252\002\016Metamoto.Types'),
  serialized_pb=_b('\n\"metamoto/types/traffic_light.proto\x12\x0emetamoto.types\x1a\x19metamoto/types/pose.proto\x1a\x1ametamoto/types/shape.proto\x1a)metamoto/types/signal_configuration.proto\"\xc3\x05\n\x0cTrafficLight\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tsignal_id\x18\x02 \x01(\t\x12\"\n\x04pose\x18\x03 \x01(\x0b\x32\x14.metamoto.types.Pose\x12$\n\x05shape\x18\x04 \x01(\x0b\x32\x15.metamoto.types.Shape\x12/\n\x04type\x18\x05 \x01(\x0e\x32!.metamoto.types.TrafficLight.Type\x12\x31\n\x05\x63olor\x18\x06 \x01(\x0e\x32\".metamoto.types.TrafficLight.Color\x12/\n\x04mode\x18\x07 \x01(\x0e\x32!.metamoto.types.TrafficLight.Mode\x12\x17\n\x0fintersection_id\x18\x08 \x01(\t\x12\x45\n\x05state\x18\t \x01(\x0b\x32\x36.metamoto.types.SignalConfiguration.Signal.SignalState\x12G\n\nbulb_types\x18\n \x03(\x0b\x32\x33.metamoto.types.SignalConfiguration.Signal.BulbType\"p\n\x04Type\x12\x10\n\x0cTYPE_UNKNOWN\x10\x00\x12\x0e\n\nTYPE_OTHER\x10\x01\x12\n\n\x06NORMAL\x10\x02\x12\x08\n\x04LEFT\x10\x03\x12\x11\n\rLEFT_STRAIGHT\x10\x04\x12\t\n\x05RIGHT\x10\x05\x12\x12\n\x0eRIGHT_STRAIGHT\x10\x06\"K\n\x05\x43olor\x12\x11\n\rCOLOR_UNKNOWN\x10\x00\x12\x0f\n\x0b\x43OLOR_OTHER\x10\x01\x12\x07\n\x03RED\x10\x02\x12\n\n\x06YELLOW\x10\x03\x12\t\n\x05GREEN\x10\x04\"M\n\x04Mode\x12\x10\n\x0cMODE_UNKNOWN\x10\x00\x12\x0e\n\nMODE_OTHER\x10\x01\x12\x07\n\x03OFF\x10\x02\x12\x0c\n\x08\x43ONSTANT\x10\x03\x12\x0c\n\x08\x42LINKING\x10\x04\x42\x11\xaa\x02\x0eMetamoto.Typesb\x06proto3')
  ,
  dependencies=[metamoto_dot_types_dot_pose__pb2.DESCRIPTOR,metamoto_dot_types_dot_shape__pb2.DESCRIPTOR,metamoto_dot_types_dot_signal__configuration__pb2.DESCRIPTOR,])



_TRAFFICLIGHT_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='metamoto.types.TrafficLight.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TYPE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TYPE_OTHER', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NORMAL', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEFT', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEFT_STRAIGHT', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT_STRAIGHT', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=592,
  serialized_end=704,
)
_sym_db.RegisterEnumDescriptor(_TRAFFICLIGHT_TYPE)

_TRAFFICLIGHT_COLOR = _descriptor.EnumDescriptor(
  name='Color',
  full_name='metamoto.types.TrafficLight.Color',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COLOR_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COLOR_OTHER', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RED', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='YELLOW', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GREEN', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=706,
  serialized_end=781,
)
_sym_db.RegisterEnumDescriptor(_TRAFFICLIGHT_COLOR)

_TRAFFICLIGHT_MODE = _descriptor.EnumDescriptor(
  name='Mode',
  full_name='metamoto.types.TrafficLight.Mode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MODE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MODE_OTHER', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OFF', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONSTANT', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BLINKING', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=783,
  serialized_end=860,
)
_sym_db.RegisterEnumDescriptor(_TRAFFICLIGHT_MODE)


_TRAFFICLIGHT = _descriptor.Descriptor(
  name='TrafficLight',
  full_name='metamoto.types.TrafficLight',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='metamoto.types.TrafficLight.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signal_id', full_name='metamoto.types.TrafficLight.signal_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pose', full_name='metamoto.types.TrafficLight.pose', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shape', full_name='metamoto.types.TrafficLight.shape', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='metamoto.types.TrafficLight.type', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='color', full_name='metamoto.types.TrafficLight.color', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mode', full_name='metamoto.types.TrafficLight.mode', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='intersection_id', full_name='metamoto.types.TrafficLight.intersection_id', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='metamoto.types.TrafficLight.state', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bulb_types', full_name='metamoto.types.TrafficLight.bulb_types', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TRAFFICLIGHT_TYPE,
    _TRAFFICLIGHT_COLOR,
    _TRAFFICLIGHT_MODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=860,
)

_TRAFFICLIGHT.fields_by_name['pose'].message_type = metamoto_dot_types_dot_pose__pb2._POSE
_TRAFFICLIGHT.fields_by_name['shape'].message_type = metamoto_dot_types_dot_shape__pb2._SHAPE
_TRAFFICLIGHT.fields_by_name['type'].enum_type = _TRAFFICLIGHT_TYPE
_TRAFFICLIGHT.fields_by_name['color'].enum_type = _TRAFFICLIGHT_COLOR
_TRAFFICLIGHT.fields_by_name['mode'].enum_type = _TRAFFICLIGHT_MODE
_TRAFFICLIGHT.fields_by_name['state'].message_type = metamoto_dot_types_dot_signal__configuration__pb2._SIGNALCONFIGURATION_SIGNAL_SIGNALSTATE
_TRAFFICLIGHT.fields_by_name['bulb_types'].message_type = metamoto_dot_types_dot_signal__configuration__pb2._SIGNALCONFIGURATION_SIGNAL_BULBTYPE
_TRAFFICLIGHT_TYPE.containing_type = _TRAFFICLIGHT
_TRAFFICLIGHT_COLOR.containing_type = _TRAFFICLIGHT
_TRAFFICLIGHT_MODE.containing_type = _TRAFFICLIGHT
DESCRIPTOR.message_types_by_name['TrafficLight'] = _TRAFFICLIGHT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TrafficLight = _reflection.GeneratedProtocolMessageType('TrafficLight', (_message.Message,), dict(
  DESCRIPTOR = _TRAFFICLIGHT,
  __module__ = 'metamoto.types.traffic_light_pb2'
  # @@protoc_insertion_point(class_scope:metamoto.types.TrafficLight)
  ))
_sym_db.RegisterMessage(TrafficLight)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
