# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from delphi_mrr_msgs/LrosCarCfgFord.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class LrosCarCfgFord(genpy.Message):
  _md5sum = "6b40261fec542e406fc60f9b9b2d121a"
  _type = "delphi_mrr_msgs/LrosCarCfgFord"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header

int8 	    k_radar_azimuth_polarity
float32  	can_fa_vert_ground_offset
float32  	can_fa_vert_lower_limit
float32  	can_fa_vert_upper_limit
uint8 	  can_lros_carcfgvehtype_ford
uint8 	  can_lros_carcfgengine_ford

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id
"""
  __slots__ = ['header','k_radar_azimuth_polarity','can_fa_vert_ground_offset','can_fa_vert_lower_limit','can_fa_vert_upper_limit','can_lros_carcfgvehtype_ford','can_lros_carcfgengine_ford']
  _slot_types = ['std_msgs/Header','int8','float32','float32','float32','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,k_radar_azimuth_polarity,can_fa_vert_ground_offset,can_fa_vert_lower_limit,can_fa_vert_upper_limit,can_lros_carcfgvehtype_ford,can_lros_carcfgengine_ford

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LrosCarCfgFord, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.k_radar_azimuth_polarity is None:
        self.k_radar_azimuth_polarity = 0
      if self.can_fa_vert_ground_offset is None:
        self.can_fa_vert_ground_offset = 0.
      if self.can_fa_vert_lower_limit is None:
        self.can_fa_vert_lower_limit = 0.
      if self.can_fa_vert_upper_limit is None:
        self.can_fa_vert_upper_limit = 0.
      if self.can_lros_carcfgvehtype_ford is None:
        self.can_lros_carcfgvehtype_ford = 0
      if self.can_lros_carcfgengine_ford is None:
        self.can_lros_carcfgengine_ford = 0
    else:
      self.header = std_msgs.msg.Header()
      self.k_radar_azimuth_polarity = 0
      self.can_fa_vert_ground_offset = 0.
      self.can_fa_vert_lower_limit = 0.
      self.can_fa_vert_upper_limit = 0.
      self.can_lros_carcfgvehtype_ford = 0
      self.can_lros_carcfgengine_ford = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_b3f2B().pack(_x.k_radar_azimuth_polarity, _x.can_fa_vert_ground_offset, _x.can_fa_vert_lower_limit, _x.can_fa_vert_upper_limit, _x.can_lros_carcfgvehtype_ford, _x.can_lros_carcfgengine_ford))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 15
      (_x.k_radar_azimuth_polarity, _x.can_fa_vert_ground_offset, _x.can_fa_vert_lower_limit, _x.can_fa_vert_upper_limit, _x.can_lros_carcfgvehtype_ford, _x.can_lros_carcfgengine_ford,) = _get_struct_b3f2B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_b3f2B().pack(_x.k_radar_azimuth_polarity, _x.can_fa_vert_ground_offset, _x.can_fa_vert_lower_limit, _x.can_fa_vert_upper_limit, _x.can_lros_carcfgvehtype_ford, _x.can_lros_carcfgengine_ford))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 15
      (_x.k_radar_azimuth_polarity, _x.can_fa_vert_ground_offset, _x.can_fa_vert_lower_limit, _x.can_fa_vert_upper_limit, _x.can_lros_carcfgvehtype_ford, _x.can_lros_carcfgengine_ford,) = _get_struct_b3f2B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_b3f2B = None
def _get_struct_b3f2B():
    global _struct_b3f2B
    if _struct_b3f2B is None:
        _struct_b3f2B = struct.Struct("<b3f2B")
    return _struct_b3f2B
