// Generated by gencpp from file delphi_esr_msgs/EsrStatus4.msg
// DO NOT EDIT!


#ifndef DELPHI_ESR_MSGS_MESSAGE_ESRSTATUS4_H
#define DELPHI_ESR_MSGS_MESSAGE_ESRSTATUS4_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace delphi_esr_msgs
{
template <class ContainerAllocator>
struct EsrStatus4_
{
  typedef EsrStatus4_<ContainerAllocator> Type;

  EsrStatus4_()
    : header()
    , canmsg()
    , rolling_count3(0)
    , mrlr_mode(0)
    , patial_blockage(false)
    , side_lobe_blockage(false)
    , lr_only_grating_lobe_det(false)
    , truck_target_det(false)
    , path_id_acc(0)
    , path_id_cmmb_move(0)
    , path_id_cmmb_stat(0)
    , path_id_fcw_move(0)
    , path_id_fcw_stat(0)
    , path_id_acc_stat(0)
    , auto_algin_angle(0.0)  {
    }
  EsrStatus4_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , canmsg(_alloc)
    , rolling_count3(0)
    , mrlr_mode(0)
    , patial_blockage(false)
    , side_lobe_blockage(false)
    , lr_only_grating_lobe_det(false)
    , truck_target_det(false)
    , path_id_acc(0)
    , path_id_cmmb_move(0)
    , path_id_cmmb_stat(0)
    , path_id_fcw_move(0)
    , path_id_fcw_stat(0)
    , path_id_acc_stat(0)
    , auto_algin_angle(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _canmsg_type;
  _canmsg_type canmsg;

   typedef uint8_t _rolling_count3_type;
  _rolling_count3_type rolling_count3;

   typedef uint8_t _mrlr_mode_type;
  _mrlr_mode_type mrlr_mode;

   typedef uint8_t _patial_blockage_type;
  _patial_blockage_type patial_blockage;

   typedef uint8_t _side_lobe_blockage_type;
  _side_lobe_blockage_type side_lobe_blockage;

   typedef uint8_t _lr_only_grating_lobe_det_type;
  _lr_only_grating_lobe_det_type lr_only_grating_lobe_det;

   typedef uint8_t _truck_target_det_type;
  _truck_target_det_type truck_target_det;

   typedef uint8_t _path_id_acc_type;
  _path_id_acc_type path_id_acc;

   typedef uint8_t _path_id_cmmb_move_type;
  _path_id_cmmb_move_type path_id_cmmb_move;

   typedef uint8_t _path_id_cmmb_stat_type;
  _path_id_cmmb_stat_type path_id_cmmb_stat;

   typedef uint8_t _path_id_fcw_move_type;
  _path_id_fcw_move_type path_id_fcw_move;

   typedef uint8_t _path_id_fcw_stat_type;
  _path_id_fcw_stat_type path_id_fcw_stat;

   typedef uint8_t _path_id_acc_stat_type;
  _path_id_acc_stat_type path_id_acc_stat;

   typedef float _auto_algin_angle_type;
  _auto_algin_angle_type auto_algin_angle;





  typedef boost::shared_ptr< ::delphi_esr_msgs::EsrStatus4_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::delphi_esr_msgs::EsrStatus4_<ContainerAllocator> const> ConstPtr;

}; // struct EsrStatus4_

typedef ::delphi_esr_msgs::EsrStatus4_<std::allocator<void> > EsrStatus4;

typedef boost::shared_ptr< ::delphi_esr_msgs::EsrStatus4 > EsrStatus4Ptr;
typedef boost::shared_ptr< ::delphi_esr_msgs::EsrStatus4 const> EsrStatus4ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::delphi_esr_msgs::EsrStatus4_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::delphi_esr_msgs::EsrStatus4_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace delphi_esr_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'delphi_esr_msgs': ['/metamoto/catkin_ws/src/astuff_sensor_msgs/delphi_esr_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::delphi_esr_msgs::EsrStatus4_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delphi_esr_msgs::EsrStatus4_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delphi_esr_msgs::EsrStatus4_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delphi_esr_msgs::EsrStatus4_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delphi_esr_msgs::EsrStatus4_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delphi_esr_msgs::EsrStatus4_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::delphi_esr_msgs::EsrStatus4_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f7cf3bcce6d7e6a3b7b68f3a7c2726e4";
  }

  static const char* value(const ::delphi_esr_msgs::EsrStatus4_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf7cf3bcce6d7e6a3ULL;
  static const uint64_t static_value2 = 0xb7b68f3a7c2726e4ULL;
};

template<class ContainerAllocator>
struct DataType< ::delphi_esr_msgs::EsrStatus4_<ContainerAllocator> >
{
  static const char* value()
  {
    return "delphi_esr_msgs/EsrStatus4";
  }

  static const char* value(const ::delphi_esr_msgs::EsrStatus4_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::delphi_esr_msgs::EsrStatus4_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
\n\
# ESR status4\n\
string      canmsg\n\
uint8       rolling_count3\n\
uint8       mrlr_mode\n\
bool        patial_blockage\n\
bool        side_lobe_blockage\n\
bool        lr_only_grating_lobe_det\n\
bool        truck_target_det\n\
uint8       path_id_acc\n\
uint8       path_id_cmmb_move\n\
uint8       path_id_cmmb_stat\n\
uint8       path_id_fcw_move\n\
uint8       path_id_fcw_stat\n\
uint8       path_id_acc_stat\n\
float32     auto_algin_angle\n\
\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::delphi_esr_msgs::EsrStatus4_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::delphi_esr_msgs::EsrStatus4_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.canmsg);
      stream.next(m.rolling_count3);
      stream.next(m.mrlr_mode);
      stream.next(m.patial_blockage);
      stream.next(m.side_lobe_blockage);
      stream.next(m.lr_only_grating_lobe_det);
      stream.next(m.truck_target_det);
      stream.next(m.path_id_acc);
      stream.next(m.path_id_cmmb_move);
      stream.next(m.path_id_cmmb_stat);
      stream.next(m.path_id_fcw_move);
      stream.next(m.path_id_fcw_stat);
      stream.next(m.path_id_acc_stat);
      stream.next(m.auto_algin_angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EsrStatus4_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::delphi_esr_msgs::EsrStatus4_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::delphi_esr_msgs::EsrStatus4_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "canmsg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.canmsg);
    s << indent << "rolling_count3: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.rolling_count3);
    s << indent << "mrlr_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mrlr_mode);
    s << indent << "patial_blockage: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.patial_blockage);
    s << indent << "side_lobe_blockage: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.side_lobe_blockage);
    s << indent << "lr_only_grating_lobe_det: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.lr_only_grating_lobe_det);
    s << indent << "truck_target_det: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.truck_target_det);
    s << indent << "path_id_acc: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.path_id_acc);
    s << indent << "path_id_cmmb_move: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.path_id_cmmb_move);
    s << indent << "path_id_cmmb_stat: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.path_id_cmmb_stat);
    s << indent << "path_id_fcw_move: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.path_id_fcw_move);
    s << indent << "path_id_fcw_stat: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.path_id_fcw_stat);
    s << indent << "path_id_acc_stat: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.path_id_acc_stat);
    s << indent << "auto_algin_angle: ";
    Printer<float>::stream(s, indent + "  ", v.auto_algin_angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DELPHI_ESR_MSGS_MESSAGE_ESRSTATUS4_H
