// Generated by gencpp from file delphi_mrr_msgs/LrosCarCfgFord.msg
// DO NOT EDIT!


#ifndef DELPHI_MRR_MSGS_MESSAGE_LROSCARCFGFORD_H
#define DELPHI_MRR_MSGS_MESSAGE_LROSCARCFGFORD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace delphi_mrr_msgs
{
template <class ContainerAllocator>
struct LrosCarCfgFord_
{
  typedef LrosCarCfgFord_<ContainerAllocator> Type;

  LrosCarCfgFord_()
    : header()
    , k_radar_azimuth_polarity(0)
    , can_fa_vert_ground_offset(0.0)
    , can_fa_vert_lower_limit(0.0)
    , can_fa_vert_upper_limit(0.0)
    , can_lros_carcfgvehtype_ford(0)
    , can_lros_carcfgengine_ford(0)  {
    }
  LrosCarCfgFord_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , k_radar_azimuth_polarity(0)
    , can_fa_vert_ground_offset(0.0)
    , can_fa_vert_lower_limit(0.0)
    , can_fa_vert_upper_limit(0.0)
    , can_lros_carcfgvehtype_ford(0)
    , can_lros_carcfgengine_ford(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _k_radar_azimuth_polarity_type;
  _k_radar_azimuth_polarity_type k_radar_azimuth_polarity;

   typedef float _can_fa_vert_ground_offset_type;
  _can_fa_vert_ground_offset_type can_fa_vert_ground_offset;

   typedef float _can_fa_vert_lower_limit_type;
  _can_fa_vert_lower_limit_type can_fa_vert_lower_limit;

   typedef float _can_fa_vert_upper_limit_type;
  _can_fa_vert_upper_limit_type can_fa_vert_upper_limit;

   typedef uint8_t _can_lros_carcfgvehtype_ford_type;
  _can_lros_carcfgvehtype_ford_type can_lros_carcfgvehtype_ford;

   typedef uint8_t _can_lros_carcfgengine_ford_type;
  _can_lros_carcfgengine_ford_type can_lros_carcfgengine_ford;





  typedef boost::shared_ptr< ::delphi_mrr_msgs::LrosCarCfgFord_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::delphi_mrr_msgs::LrosCarCfgFord_<ContainerAllocator> const> ConstPtr;

}; // struct LrosCarCfgFord_

typedef ::delphi_mrr_msgs::LrosCarCfgFord_<std::allocator<void> > LrosCarCfgFord;

typedef boost::shared_ptr< ::delphi_mrr_msgs::LrosCarCfgFord > LrosCarCfgFordPtr;
typedef boost::shared_ptr< ::delphi_mrr_msgs::LrosCarCfgFord const> LrosCarCfgFordConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::delphi_mrr_msgs::LrosCarCfgFord_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::delphi_mrr_msgs::LrosCarCfgFord_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace delphi_mrr_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'delphi_mrr_msgs': ['/metamoto/catkin_ws/src/astuff_sensor_msgs/delphi_mrr_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::delphi_mrr_msgs::LrosCarCfgFord_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delphi_mrr_msgs::LrosCarCfgFord_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delphi_mrr_msgs::LrosCarCfgFord_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delphi_mrr_msgs::LrosCarCfgFord_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delphi_mrr_msgs::LrosCarCfgFord_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delphi_mrr_msgs::LrosCarCfgFord_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::delphi_mrr_msgs::LrosCarCfgFord_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6b40261fec542e406fc60f9b9b2d121a";
  }

  static const char* value(const ::delphi_mrr_msgs::LrosCarCfgFord_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6b40261fec542e40ULL;
  static const uint64_t static_value2 = 0x6fc60f9b9b2d121aULL;
};

template<class ContainerAllocator>
struct DataType< ::delphi_mrr_msgs::LrosCarCfgFord_<ContainerAllocator> >
{
  static const char* value()
  {
    return "delphi_mrr_msgs/LrosCarCfgFord";
  }

  static const char* value(const ::delphi_mrr_msgs::LrosCarCfgFord_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::delphi_mrr_msgs::LrosCarCfgFord_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
\n\
int8 	    k_radar_azimuth_polarity\n\
float32  	can_fa_vert_ground_offset\n\
float32  	can_fa_vert_lower_limit\n\
float32  	can_fa_vert_upper_limit\n\
uint8 	  can_lros_carcfgvehtype_ford\n\
uint8 	  can_lros_carcfgengine_ford\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::delphi_mrr_msgs::LrosCarCfgFord_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::delphi_mrr_msgs::LrosCarCfgFord_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.k_radar_azimuth_polarity);
      stream.next(m.can_fa_vert_ground_offset);
      stream.next(m.can_fa_vert_lower_limit);
      stream.next(m.can_fa_vert_upper_limit);
      stream.next(m.can_lros_carcfgvehtype_ford);
      stream.next(m.can_lros_carcfgengine_ford);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LrosCarCfgFord_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::delphi_mrr_msgs::LrosCarCfgFord_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::delphi_mrr_msgs::LrosCarCfgFord_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "k_radar_azimuth_polarity: ";
    Printer<int8_t>::stream(s, indent + "  ", v.k_radar_azimuth_polarity);
    s << indent << "can_fa_vert_ground_offset: ";
    Printer<float>::stream(s, indent + "  ", v.can_fa_vert_ground_offset);
    s << indent << "can_fa_vert_lower_limit: ";
    Printer<float>::stream(s, indent + "  ", v.can_fa_vert_lower_limit);
    s << indent << "can_fa_vert_upper_limit: ";
    Printer<float>::stream(s, indent + "  ", v.can_fa_vert_upper_limit);
    s << indent << "can_lros_carcfgvehtype_ford: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.can_lros_carcfgvehtype_ford);
    s << indent << "can_lros_carcfgengine_ford: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.can_lros_carcfgengine_ford);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DELPHI_MRR_MSGS_MESSAGE_LROSCARCFGFORD_H
