// Generated by gencpp from file delphi_mrr_msgs/SystemStatus.msg
// DO NOT EDIT!


#ifndef DELPHI_MRR_MSGS_MESSAGE_SYSTEMSTATUS_H
#define DELPHI_MRR_MSGS_MESSAGE_SYSTEMSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace delphi_mrr_msgs
{
template <class ContainerAllocator>
struct SystemStatus_
{
  typedef SystemStatus_<ContainerAllocator> Type;

  SystemStatus_()
    : header()
    , can_vehicle_stat(false)
    , can_day_night_status(false)
    , can_wiper_status(false)
    , can_yaw_rate_validity(false)
    , can_yaw_rate(0.0)
    , can_vehicle_speed_validity(false)
    , can_vehicle_speed_direction(false)
    , can_vehicle_speed(0.0)  {
    }
  SystemStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , can_vehicle_stat(false)
    , can_day_night_status(false)
    , can_wiper_status(false)
    , can_yaw_rate_validity(false)
    , can_yaw_rate(0.0)
    , can_vehicle_speed_validity(false)
    , can_vehicle_speed_direction(false)
    , can_vehicle_speed(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _can_vehicle_stat_type;
  _can_vehicle_stat_type can_vehicle_stat;

   typedef uint8_t _can_day_night_status_type;
  _can_day_night_status_type can_day_night_status;

   typedef uint8_t _can_wiper_status_type;
  _can_wiper_status_type can_wiper_status;

   typedef uint8_t _can_yaw_rate_validity_type;
  _can_yaw_rate_validity_type can_yaw_rate_validity;

   typedef float _can_yaw_rate_type;
  _can_yaw_rate_type can_yaw_rate;

   typedef uint8_t _can_vehicle_speed_validity_type;
  _can_vehicle_speed_validity_type can_vehicle_speed_validity;

   typedef uint8_t _can_vehicle_speed_direction_type;
  _can_vehicle_speed_direction_type can_vehicle_speed_direction;

   typedef float _can_vehicle_speed_type;
  _can_vehicle_speed_type can_vehicle_speed;





  typedef boost::shared_ptr< ::delphi_mrr_msgs::SystemStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::delphi_mrr_msgs::SystemStatus_<ContainerAllocator> const> ConstPtr;

}; // struct SystemStatus_

typedef ::delphi_mrr_msgs::SystemStatus_<std::allocator<void> > SystemStatus;

typedef boost::shared_ptr< ::delphi_mrr_msgs::SystemStatus > SystemStatusPtr;
typedef boost::shared_ptr< ::delphi_mrr_msgs::SystemStatus const> SystemStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::delphi_mrr_msgs::SystemStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::delphi_mrr_msgs::SystemStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace delphi_mrr_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'delphi_mrr_msgs': ['/metamoto/catkin_ws/src/astuff_sensor_msgs/delphi_mrr_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::delphi_mrr_msgs::SystemStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delphi_mrr_msgs::SystemStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delphi_mrr_msgs::SystemStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delphi_mrr_msgs::SystemStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delphi_mrr_msgs::SystemStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delphi_mrr_msgs::SystemStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::delphi_mrr_msgs::SystemStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f95e8b91cc7c4107288a89a3d6af6f1d";
  }

  static const char* value(const ::delphi_mrr_msgs::SystemStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf95e8b91cc7c4107ULL;
  static const uint64_t static_value2 = 0x288a89a3d6af6f1dULL;
};

template<class ContainerAllocator>
struct DataType< ::delphi_mrr_msgs::SystemStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "delphi_mrr_msgs/SystemStatus";
  }

  static const char* value(const ::delphi_mrr_msgs::SystemStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::delphi_mrr_msgs::SystemStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
\n\
bool    can_vehicle_stat\n\
bool    can_day_night_status\n\
bool    can_wiper_status\n\
bool    can_yaw_rate_validity\n\
float32 can_yaw_rate\n\
bool    can_vehicle_speed_validity\n\
bool    can_vehicle_speed_direction\n\
float32 can_vehicle_speed\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::delphi_mrr_msgs::SystemStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::delphi_mrr_msgs::SystemStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.can_vehicle_stat);
      stream.next(m.can_day_night_status);
      stream.next(m.can_wiper_status);
      stream.next(m.can_yaw_rate_validity);
      stream.next(m.can_yaw_rate);
      stream.next(m.can_vehicle_speed_validity);
      stream.next(m.can_vehicle_speed_direction);
      stream.next(m.can_vehicle_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SystemStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::delphi_mrr_msgs::SystemStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::delphi_mrr_msgs::SystemStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "can_vehicle_stat: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.can_vehicle_stat);
    s << indent << "can_day_night_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.can_day_night_status);
    s << indent << "can_wiper_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.can_wiper_status);
    s << indent << "can_yaw_rate_validity: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.can_yaw_rate_validity);
    s << indent << "can_yaw_rate: ";
    Printer<float>::stream(s, indent + "  ", v.can_yaw_rate);
    s << indent << "can_vehicle_speed_validity: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.can_vehicle_speed_validity);
    s << indent << "can_vehicle_speed_direction: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.can_vehicle_speed_direction);
    s << indent << "can_vehicle_speed: ";
    Printer<float>::stream(s, indent + "  ", v.can_vehicle_speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DELPHI_MRR_MSGS_MESSAGE_SYSTEMSTATUS_H
