# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from delphi_mrr_msgs/Detection.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class Detection(genpy.Message):
  _md5sum = "41bb0647e974bbe3192fea3dcc96ae90"
  _type = "delphi_mrr_msgs/Detection"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header

uint8    detection_id
uint8    confid_azimuth
bool     super_res_target
bool     nd_target
bool     host_veh_clutter
bool     valid_level
float64  azimuth
uint16   range
uint16   range_rate
uint8    amplitude
uint8    index2lsb

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id
"""
  __slots__ = ['header','detection_id','confid_azimuth','super_res_target','nd_target','host_veh_clutter','valid_level','azimuth','range','range_rate','amplitude','index2lsb']
  _slot_types = ['std_msgs/Header','uint8','uint8','bool','bool','bool','bool','float64','uint16','uint16','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,detection_id,confid_azimuth,super_res_target,nd_target,host_veh_clutter,valid_level,azimuth,range,range_rate,amplitude,index2lsb

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Detection, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.detection_id is None:
        self.detection_id = 0
      if self.confid_azimuth is None:
        self.confid_azimuth = 0
      if self.super_res_target is None:
        self.super_res_target = False
      if self.nd_target is None:
        self.nd_target = False
      if self.host_veh_clutter is None:
        self.host_veh_clutter = False
      if self.valid_level is None:
        self.valid_level = False
      if self.azimuth is None:
        self.azimuth = 0.
      if self.range is None:
        self.range = 0
      if self.range_rate is None:
        self.range_rate = 0
      if self.amplitude is None:
        self.amplitude = 0
      if self.index2lsb is None:
        self.index2lsb = 0
    else:
      self.header = std_msgs.msg.Header()
      self.detection_id = 0
      self.confid_azimuth = 0
      self.super_res_target = False
      self.nd_target = False
      self.host_veh_clutter = False
      self.valid_level = False
      self.azimuth = 0.
      self.range = 0
      self.range_rate = 0
      self.amplitude = 0
      self.index2lsb = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_6Bd2H2B().pack(_x.detection_id, _x.confid_azimuth, _x.super_res_target, _x.nd_target, _x.host_veh_clutter, _x.valid_level, _x.azimuth, _x.range, _x.range_rate, _x.amplitude, _x.index2lsb))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 20
      (_x.detection_id, _x.confid_azimuth, _x.super_res_target, _x.nd_target, _x.host_veh_clutter, _x.valid_level, _x.azimuth, _x.range, _x.range_rate, _x.amplitude, _x.index2lsb,) = _get_struct_6Bd2H2B().unpack(str[start:end])
      self.super_res_target = bool(self.super_res_target)
      self.nd_target = bool(self.nd_target)
      self.host_veh_clutter = bool(self.host_veh_clutter)
      self.valid_level = bool(self.valid_level)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_6Bd2H2B().pack(_x.detection_id, _x.confid_azimuth, _x.super_res_target, _x.nd_target, _x.host_veh_clutter, _x.valid_level, _x.azimuth, _x.range, _x.range_rate, _x.amplitude, _x.index2lsb))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 20
      (_x.detection_id, _x.confid_azimuth, _x.super_res_target, _x.nd_target, _x.host_veh_clutter, _x.valid_level, _x.azimuth, _x.range, _x.range_rate, _x.amplitude, _x.index2lsb,) = _get_struct_6Bd2H2B().unpack(str[start:end])
      self.super_res_target = bool(self.super_res_target)
      self.nd_target = bool(self.nd_target)
      self.host_veh_clutter = bool(self.host_veh_clutter)
      self.valid_level = bool(self.valid_level)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6Bd2H2B = None
def _get_struct_6Bd2H2B():
    global _struct_6Bd2H2B
    if _struct_6Bd2H2B is None:
        _struct_6Bd2H2B = struct.Struct("<6Bd2H2B")
    return _struct_6Bd2H2B
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
