// Generated by gencpp from file delphi_mrr_msgs/MrrControlAlignment.msg
// DO NOT EDIT!


#ifndef DELPHI_MRR_MSGS_MESSAGE_MRRCONTROLALIGNMENT_H
#define DELPHI_MRR_MSGS_MESSAGE_MRRCONTROLALIGNMENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace delphi_mrr_msgs
{
template <class ContainerAllocator>
struct MrrControlAlignment_
{
  typedef MrrControlAlignment_<ContainerAllocator> Type;

  MrrControlAlignment_()
    : header()
    , can_fac_align_cmd3(false)
    , can_fac_align_cmd2(false)
    , can_fac_align_cmd1(false)  {
    }
  MrrControlAlignment_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , can_fac_align_cmd3(false)
    , can_fac_align_cmd2(false)
    , can_fac_align_cmd1(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _can_fac_align_cmd3_type;
  _can_fac_align_cmd3_type can_fac_align_cmd3;

   typedef uint8_t _can_fac_align_cmd2_type;
  _can_fac_align_cmd2_type can_fac_align_cmd2;

   typedef uint8_t _can_fac_align_cmd1_type;
  _can_fac_align_cmd1_type can_fac_align_cmd1;





  typedef boost::shared_ptr< ::delphi_mrr_msgs::MrrControlAlignment_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::delphi_mrr_msgs::MrrControlAlignment_<ContainerAllocator> const> ConstPtr;

}; // struct MrrControlAlignment_

typedef ::delphi_mrr_msgs::MrrControlAlignment_<std::allocator<void> > MrrControlAlignment;

typedef boost::shared_ptr< ::delphi_mrr_msgs::MrrControlAlignment > MrrControlAlignmentPtr;
typedef boost::shared_ptr< ::delphi_mrr_msgs::MrrControlAlignment const> MrrControlAlignmentConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::delphi_mrr_msgs::MrrControlAlignment_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::delphi_mrr_msgs::MrrControlAlignment_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace delphi_mrr_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'delphi_mrr_msgs': ['/metamoto/catkin_ws/src/astuff_sensor_msgs/delphi_mrr_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::delphi_mrr_msgs::MrrControlAlignment_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delphi_mrr_msgs::MrrControlAlignment_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delphi_mrr_msgs::MrrControlAlignment_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delphi_mrr_msgs::MrrControlAlignment_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delphi_mrr_msgs::MrrControlAlignment_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delphi_mrr_msgs::MrrControlAlignment_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::delphi_mrr_msgs::MrrControlAlignment_<ContainerAllocator> >
{
  static const char* value()
  {
    return "022c142d4c445433eb445902d2e2f141";
  }

  static const char* value(const ::delphi_mrr_msgs::MrrControlAlignment_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x022c142d4c445433ULL;
  static const uint64_t static_value2 = 0xeb445902d2e2f141ULL;
};

template<class ContainerAllocator>
struct DataType< ::delphi_mrr_msgs::MrrControlAlignment_<ContainerAllocator> >
{
  static const char* value()
  {
    return "delphi_mrr_msgs/MrrControlAlignment";
  }

  static const char* value(const ::delphi_mrr_msgs::MrrControlAlignment_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::delphi_mrr_msgs::MrrControlAlignment_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
\n\
bool can_fac_align_cmd3\n\
bool can_fac_align_cmd2\n\
bool can_fac_align_cmd1\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::delphi_mrr_msgs::MrrControlAlignment_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::delphi_mrr_msgs::MrrControlAlignment_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.can_fac_align_cmd3);
      stream.next(m.can_fac_align_cmd2);
      stream.next(m.can_fac_align_cmd1);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MrrControlAlignment_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::delphi_mrr_msgs::MrrControlAlignment_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::delphi_mrr_msgs::MrrControlAlignment_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "can_fac_align_cmd3: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.can_fac_align_cmd3);
    s << indent << "can_fac_align_cmd2: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.can_fac_align_cmd2);
    s << indent << "can_fac_align_cmd1: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.can_fac_align_cmd1);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DELPHI_MRR_MSGS_MESSAGE_MRRCONTROLALIGNMENT_H
