# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from delphi_mrr_msgs/SystemStatus.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class SystemStatus(genpy.Message):
  _md5sum = "f95e8b91cc7c4107288a89a3d6af6f1d"
  _type = "delphi_mrr_msgs/SystemStatus"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header

bool    can_vehicle_stat
bool    can_day_night_status
bool    can_wiper_status
bool    can_yaw_rate_validity
float32 can_yaw_rate
bool    can_vehicle_speed_validity
bool    can_vehicle_speed_direction
float32 can_vehicle_speed

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id
"""
  __slots__ = ['header','can_vehicle_stat','can_day_night_status','can_wiper_status','can_yaw_rate_validity','can_yaw_rate','can_vehicle_speed_validity','can_vehicle_speed_direction','can_vehicle_speed']
  _slot_types = ['std_msgs/Header','bool','bool','bool','bool','float32','bool','bool','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,can_vehicle_stat,can_day_night_status,can_wiper_status,can_yaw_rate_validity,can_yaw_rate,can_vehicle_speed_validity,can_vehicle_speed_direction,can_vehicle_speed

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SystemStatus, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.can_vehicle_stat is None:
        self.can_vehicle_stat = False
      if self.can_day_night_status is None:
        self.can_day_night_status = False
      if self.can_wiper_status is None:
        self.can_wiper_status = False
      if self.can_yaw_rate_validity is None:
        self.can_yaw_rate_validity = False
      if self.can_yaw_rate is None:
        self.can_yaw_rate = 0.
      if self.can_vehicle_speed_validity is None:
        self.can_vehicle_speed_validity = False
      if self.can_vehicle_speed_direction is None:
        self.can_vehicle_speed_direction = False
      if self.can_vehicle_speed is None:
        self.can_vehicle_speed = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.can_vehicle_stat = False
      self.can_day_night_status = False
      self.can_wiper_status = False
      self.can_yaw_rate_validity = False
      self.can_yaw_rate = 0.
      self.can_vehicle_speed_validity = False
      self.can_vehicle_speed_direction = False
      self.can_vehicle_speed = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_4Bf2Bf().pack(_x.can_vehicle_stat, _x.can_day_night_status, _x.can_wiper_status, _x.can_yaw_rate_validity, _x.can_yaw_rate, _x.can_vehicle_speed_validity, _x.can_vehicle_speed_direction, _x.can_vehicle_speed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 14
      (_x.can_vehicle_stat, _x.can_day_night_status, _x.can_wiper_status, _x.can_yaw_rate_validity, _x.can_yaw_rate, _x.can_vehicle_speed_validity, _x.can_vehicle_speed_direction, _x.can_vehicle_speed,) = _get_struct_4Bf2Bf().unpack(str[start:end])
      self.can_vehicle_stat = bool(self.can_vehicle_stat)
      self.can_day_night_status = bool(self.can_day_night_status)
      self.can_wiper_status = bool(self.can_wiper_status)
      self.can_yaw_rate_validity = bool(self.can_yaw_rate_validity)
      self.can_vehicle_speed_validity = bool(self.can_vehicle_speed_validity)
      self.can_vehicle_speed_direction = bool(self.can_vehicle_speed_direction)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_4Bf2Bf().pack(_x.can_vehicle_stat, _x.can_day_night_status, _x.can_wiper_status, _x.can_yaw_rate_validity, _x.can_yaw_rate, _x.can_vehicle_speed_validity, _x.can_vehicle_speed_direction, _x.can_vehicle_speed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 14
      (_x.can_vehicle_stat, _x.can_day_night_status, _x.can_wiper_status, _x.can_yaw_rate_validity, _x.can_yaw_rate, _x.can_vehicle_speed_validity, _x.can_vehicle_speed_direction, _x.can_vehicle_speed,) = _get_struct_4Bf2Bf().unpack(str[start:end])
      self.can_vehicle_stat = bool(self.can_vehicle_stat)
      self.can_day_night_status = bool(self.can_day_night_status)
      self.can_wiper_status = bool(self.can_wiper_status)
      self.can_yaw_rate_validity = bool(self.can_yaw_rate_validity)
      self.can_vehicle_speed_validity = bool(self.can_vehicle_speed_validity)
      self.can_vehicle_speed_direction = bool(self.can_vehicle_speed_direction)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4Bf2Bf = None
def _get_struct_4Bf2Bf():
    global _struct_4Bf2Bf
    if _struct_4Bf2Bf is None:
        _struct_4Bf2Bf = struct.Struct("<4Bf2Bf")
    return _struct_4Bf2Bf
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
