# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from delphi_mrr_msgs/SystemAlignment2.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class SystemAlignment2(genpy.Message):
  _md5sum = "fab1b79e32d15c3fd6d3030b565850a5"
  _type = "delphi_mrr_msgs/SystemAlignment2"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header

uint8 	 can_serv_align_updates_need
bool     can_serv_align_type
uint8 	 can_radar_height
uint8 	 can_radar_fov_mr
uint8 	 can_radar_fov_rr
uint8 	 can_align_enable
float32  can_angle_mounting_hoffset
uint8 	 can_aalign_avg_ctr_total

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id
"""
  __slots__ = ['header','can_serv_align_updates_need','can_serv_align_type','can_radar_height','can_radar_fov_mr','can_radar_fov_rr','can_align_enable','can_angle_mounting_hoffset','can_aalign_avg_ctr_total']
  _slot_types = ['std_msgs/Header','uint8','bool','uint8','uint8','uint8','uint8','float32','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,can_serv_align_updates_need,can_serv_align_type,can_radar_height,can_radar_fov_mr,can_radar_fov_rr,can_align_enable,can_angle_mounting_hoffset,can_aalign_avg_ctr_total

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SystemAlignment2, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.can_serv_align_updates_need is None:
        self.can_serv_align_updates_need = 0
      if self.can_serv_align_type is None:
        self.can_serv_align_type = False
      if self.can_radar_height is None:
        self.can_radar_height = 0
      if self.can_radar_fov_mr is None:
        self.can_radar_fov_mr = 0
      if self.can_radar_fov_rr is None:
        self.can_radar_fov_rr = 0
      if self.can_align_enable is None:
        self.can_align_enable = 0
      if self.can_angle_mounting_hoffset is None:
        self.can_angle_mounting_hoffset = 0.
      if self.can_aalign_avg_ctr_total is None:
        self.can_aalign_avg_ctr_total = 0
    else:
      self.header = std_msgs.msg.Header()
      self.can_serv_align_updates_need = 0
      self.can_serv_align_type = False
      self.can_radar_height = 0
      self.can_radar_fov_mr = 0
      self.can_radar_fov_rr = 0
      self.can_align_enable = 0
      self.can_angle_mounting_hoffset = 0.
      self.can_aalign_avg_ctr_total = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_6BfB().pack(_x.can_serv_align_updates_need, _x.can_serv_align_type, _x.can_radar_height, _x.can_radar_fov_mr, _x.can_radar_fov_rr, _x.can_align_enable, _x.can_angle_mounting_hoffset, _x.can_aalign_avg_ctr_total))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 11
      (_x.can_serv_align_updates_need, _x.can_serv_align_type, _x.can_radar_height, _x.can_radar_fov_mr, _x.can_radar_fov_rr, _x.can_align_enable, _x.can_angle_mounting_hoffset, _x.can_aalign_avg_ctr_total,) = _get_struct_6BfB().unpack(str[start:end])
      self.can_serv_align_type = bool(self.can_serv_align_type)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_6BfB().pack(_x.can_serv_align_updates_need, _x.can_serv_align_type, _x.can_radar_height, _x.can_radar_fov_mr, _x.can_radar_fov_rr, _x.can_align_enable, _x.can_angle_mounting_hoffset, _x.can_aalign_avg_ctr_total))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 11
      (_x.can_serv_align_updates_need, _x.can_serv_align_type, _x.can_radar_height, _x.can_radar_fov_mr, _x.can_radar_fov_rr, _x.can_align_enable, _x.can_angle_mounting_hoffset, _x.can_aalign_avg_ctr_total,) = _get_struct_6BfB().unpack(str[start:end])
      self.can_serv_align_type = bool(self.can_serv_align_type)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_6BfB = None
def _get_struct_6BfB():
    global _struct_6BfB
    if _struct_6BfB is None:
        _struct_6BfB = struct.Struct("<6BfB")
    return _struct_6BfB
