(cl:in-package delphi_mrr_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          K_RADAR_AZIMUTH_POLARITY-VAL
          K_RADAR_AZIMUTH_POLARITY
          CAN_FA_VERT_GROUND_OFFSET-VAL
          CAN_FA_VERT_GROUND_OFFSET
          CAN_FA_VERT_LOWER_LIMIT-VAL
          CAN_FA_VERT_LOWER_LIMIT
          CAN_FA_VERT_UPPER_LIMIT-VAL
          CAN_FA_VERT_UPPER_LIMIT
          CAN_LROS_CARCFGVEHTYPE_FORD-VAL
          CAN_LROS_CARCFGVEHTYPE_FORD
          CAN_LROS_CARCFGENGINE_FORD-VAL
          CAN_LROS_CARCFGENGINE_FORD
))