(cl:in-package delphi_mrr_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          CAN_LATERAL_MOUNTING_OFFSET-VAL
          CAN_LATERAL_MOUNTING_OFFSET
          CAN_FAC_PLATE_TILT_NUMBER-VAL
          CAN_FAC_PLATE_TILT_NUMBER
          CAN_FAC_PLATE_TILT_ANGLE-VAL
          CAN_FAC_PLATE_TILT_ANGLE
          CAN_FAC_PLATE_POSITIONS_TOTAL-VAL
          CAN_FAC_PLATE_POSITIONS_TOTAL
          CAN_FAC_ALIGN_MAX_NT-VAL
          CAN_FAC_ALIGN_MAX_NT
))