(cl:in-package delphi_mrr_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          CAN_SERV_ALIGN_UPDATES_NEED-VAL
          CAN_SERV_ALIGN_UPDATES_NEED
          CAN_SERV_ALIGN_TYPE-VAL
          CAN_SERV_ALIGN_TYPE
          CAN_RADAR_HEIGHT-VAL
          CAN_RADAR_HEIGHT
          CAN_RADAR_FOV_MR-VAL
          CAN_RADAR_FOV_MR
          CAN_RADAR_FOV_RR-VAL
          CAN_RADAR_FOV_RR
          CAN_ALIGN_ENABLE-VAL
          CAN_ALIGN_ENABLE
          CAN_ANGLE_MOUNTING_HOFFSET-VAL
          CAN_ANGLE_MOUNTING_HOFFSET
          CAN_AALIGN_AVG_CTR_TOTAL-VAL
          CAN_AALIGN_AVG_CTR_TOTAL
))