(cl:in-package delphi_esr_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          CANMSG-VAL
          CANMSG
          ROLLING_COUNT3-VAL
          ROLLING_COUNT3
          MRLR_MODE-VAL
          MRLR_MODE
          PATIAL_BLOCKAGE-VAL
          PATIAL_BLOCKAGE
          SIDE_LOBE_BLOCKAGE-VAL
          SIDE_LOBE_BLOCKAGE
          LR_ONLY_GRATING_LOBE_DET-VAL
          LR_ONLY_GRATING_LOBE_DET
          TRUCK_TARGET_DET-VAL
          TRUCK_TARGET_DET
          PATH_ID_ACC-VAL
          PATH_ID_ACC
          PATH_ID_CMMB_MOVE-VAL
          PATH_ID_CMMB_MOVE
          PATH_ID_CMMB_STAT-VAL
          PATH_ID_CMMB_STAT
          PATH_ID_FCW_MOVE-VAL
          PATH_ID_FCW_MOVE
          PATH_ID_FCW_STAT-VAL
          PATH_ID_FCW_STAT
          PATH_ID_ACC_STAT-VAL
          PATH_ID_ACC_STAT
          AUTO_ALGIN_ANGLE-VAL
          AUTO_ALGIN_ANGLE
))